export const NS = 'http://example.com/StockToPort';

export const BrowseNames = Object.freeze({
   AlignmentSensorType: 'AlignmentSensorType',
   Amplitude: 'Amplitude',
   AssetId: 'AssetId',
   AutomaticSampler1: 'Automatic Sampler #1',
   AutomaticSamplerType: 'AutomaticSamplerType',
   BeltAlignmentSensor: 'BeltAlignmentSensor',
   BeltConveyor1: 'Belt Conveyor #1',
   BeltConveyorType: 'BeltConveyorType',
   BeltLoadSensor: 'BeltLoadSensor',
   BeltSpeedSensor: 'BeltSpeedSensor',
   ConveyorMachineType: 'ConveyorMachineType',
   CumulativeEnergyUsed: 'CumulativeEnergyUsed',
   CurrentSensorType: 'CurrentSensorType',
   DeviceClass: 'DeviceClass',
   DirectionSignal: 'DirectionSignal',
   DistanceBetweenStockpiles: 'DistanceBetweenStockpiles',
   DustConcentrationSensor: 'DustConcentrationSensor',
   DustConcentrationSensorType: 'DustConcentrationSensorType',
   EmissionSpectrum: 'EmissionSpectrum',
   EngineeringUnits: 'EngineeringUnits',
   EURange: 'EURange',
   ExclusionZone: 'ExclusionZone',
   FillingRate: 'FillingRate',
   Frequency: 'Frequency',
   HumiditySensor: 'HumiditySensor',
   HumiditySensorType: 'HumiditySensorType',
   Identification: 'Identification',
   InstrumentRange: 'InstrumentRange',
   LevelSensorType: 'LevelSensorType',
   LoadingMachineType: 'LoadingMachineType',
   LoadingStateSensor: 'LoadingStateSensor',
   LoadSensor: 'LoadSensor',
   LoadSensorType: 'LoadSensorType',
   MachinePose: 'MachinePose',
   Manufacturer: 'Manufacturer',
   ManufacturerUri: 'ManufacturerUri',
   Measurement: 'Measurement',
   MiningEquipmentIdentificationType: 'MiningEquipmentIdentificationType',
   MiningEquipmentType: 'MiningEquipmentType',
   Model: 'Model',
   MotorCurrentSensor: 'MotorCurrentSensor',
   MotorTemperatureSensor: 'MotorTemperatureSensor',
   MotorVoltageSensor: 'MotorVoltageSensor',
   OperatingStateSensor: 'OperatingStateSensor',
   PositioningComplete: 'PositioningComplete',
   PositionSensor: 'PositionSensor',
   PositionSensorType: 'PositionSensorType',
   ProductInstanceUri: 'ProductInstanceUri',
   QualityIdentifier1: 'Quality Identifier #1',
   QualityIdentifierType: 'QualityIdentifierType',
   RequestForLoading: 'RequestForLoading',
   SamplingArmPositionSensor: 'SamplingArmPositionSensor',
   SamplingFrequency: 'SamplingFrequency',
   Scraper1: 'Scraper #1',
   ScraperType: 'ScraperType',
   ScreeningUnit1: 'Screening Unit #1',
   ScreeningUnitType: 'ScreeningUnitType',
   ScreenThicknessSensor: 'ScreenThicknessSensor',
   SensorType: 'SensorType',
   SerialNumber: 'SerialNumber',
   Shiploader1: 'Shiploader #1',
   ShiploaderType: 'ShiploaderType',
   ShuttleConveyor1: 'Shuttle Conveyor #1',
   ShuttleConveyorType: 'ShuttleConveyorType',
   SpeedSensor: 'SpeedSensor',
   SpeedSensorType: 'SpeedSensorType',
   StartConveyor: 'StartConveyor',
   StateSensorType: 'StateSensorType',
   StockpileColor: 'StockpileColor',
   StockpileCoordinates: 'StockpileCoordinates',
   StockpileHeight: 'StockpileHeight',
   StopConveyor: 'StopConveyor',
   StopLoading: 'StopLoading',
   StorageHall1: 'Storage Hall #1',
   StorageHallType: 'StorageHallType',
   StructuredArrayItemType: 'StructuredArrayItemType',
   TemperatureSensorType: 'TemperatureSensorType',
   TripperCar1: 'Tripper Car #1',
   TripperCarType: 'TripperCarType',
   VibrationSensor: 'VibrationSensor',
   VibrationSensorType: 'VibrationSensorType',
   VoltageSensorType: 'VoltageSensorType',
   VolumeFlowRateSensor: 'VolumeFlowRateSensor',
   VolumeFlowRateSensorType: 'VolumeFlowRateSensorType',
   WearSensorType: 'WearSensorType',
});

export const MethodIds = Object.freeze({
   LoadingMachineType_PositioningComplete: 'nsu=' + NS + ';i=54',
   LoadingMachineType_RequestForLoading: 'nsu=' + NS + ';i=55',
   LoadingMachineType_StopLoading: 'nsu=' + NS + ';i=56',
   ConveyorMachineType_StartConveyor: 'nsu=' + NS + ';i=218',
   ConveyorMachineType_StopConveyor: 'nsu=' + NS + ';i=219',
   TripperCar1_PositioningComplete: 'nsu=' + NS + ';i=640',
   TripperCar1_RequestForLoading: 'nsu=' + NS + ';i=641',
   TripperCar1_StopLoading: 'nsu=' + NS + ';i=642',
   Shiploader1_PositioningComplete: 'nsu=' + NS + ';i=911',
   Shiploader1_RequestForLoading: 'nsu=' + NS + ';i=912',
   Shiploader1_StopLoading: 'nsu=' + NS + ';i=913',
   ShuttleConveyor1_StartConveyor: 'nsu=' + NS + ';i=991',
   ShuttleConveyor1_StopConveyor: 'nsu=' + NS + ';i=992',
   Scraper1_PositioningComplete: 'nsu=' + NS + ';i=1069',
   Scraper1_RequestForLoading: 'nsu=' + NS + ';i=1070',
   Scraper1_StopLoading: 'nsu=' + NS + ';i=1071',
   BeltConveyor1_StartConveyor: 'nsu=' + NS + ';i=1149',
   BeltConveyor1_StopConveyor: 'nsu=' + NS + ';i=1150',
});

export const ObjectIds = Object.freeze({
   MiningEquipmentType_Identification: 'nsu=' + NS + ';i=45',
   ScraperType_SpeedSensor: 'nsu=' + NS + ';i=60',
   ScraperType_MotorCurrentSensor: 'nsu=' + NS + ';i=69',
   ScraperType_MotorVoltageSensor: 'nsu=' + NS + ';i=78',
   ScraperType_OperatingStateSensor: 'nsu=' + NS + ';i=87',
   ScraperType_MotorTemperatureSensor: 'nsu=' + NS + ';i=96',
   ScraperType_PositionSensor: 'nsu=' + NS + ';i=105',
   ScraperType_VibrationSensor: 'nsu=' + NS + ';i=115',
   StorageHallType_HumiditySensor: 'nsu=' + NS + ';i=129',
   StorageHallType_DustConcentrationSensor: 'nsu=' + NS + ';i=141',
   TripperCarType_SpeedSensor: 'nsu=' + NS + ';i=151',
   TripperCarType_MotorCurrentSensor: 'nsu=' + NS + ';i=160',
   TripperCarType_MotorVoltageSensor: 'nsu=' + NS + ';i=169',
   TripperCarType_OperatingStateSensor: 'nsu=' + NS + ';i=178',
   TripperCarType_MotorTemperatureSensor: 'nsu=' + NS + ';i=187',
   TripperCarType_PositionSensor: 'nsu=' + NS + ';i=196',
   TripperCarType_VibrationSensor: 'nsu=' + NS + ';i=206',
   BeltConveyorType_BeltSpeedSensor: 'nsu=' + NS + ';i=221',
   BeltConveyorType_VolumeFlowRateSensor: 'nsu=' + NS + ';i=230',
   BeltConveyorType_BeltLoadSensor: 'nsu=' + NS + ';i=239',
   BeltConveyorType_MotorCurrentSensor: 'nsu=' + NS + ';i=248',
   BeltConveyorType_MotorVoltageSensor: 'nsu=' + NS + ';i=257',
   BeltConveyorType_OperatingStateSensor: 'nsu=' + NS + ';i=266',
   BeltConveyorType_MotorTemperatureSensor: 'nsu=' + NS + ';i=275',
   BeltConveyorType_VibrationSensor: 'nsu=' + NS + ';i=285',
   BeltConveyorType_BeltAlignmentSensor: 'nsu=' + NS + ';i=296',
   ShuttleConveyorType_LoadingStateSensor: 'nsu=' + NS + ';i=306',
   ShuttleConveyorType_BeltLoadSensor: 'nsu=' + NS + ';i=315',
   ShuttleConveyorType_MotorCurrentSensor: 'nsu=' + NS + ';i=324',
   ShuttleConveyorType_MotorVoltageSensor: 'nsu=' + NS + ';i=333',
   ShuttleConveyorType_OperatingStateSensor: 'nsu=' + NS + ';i=342',
   ShuttleConveyorType_MotorTemperatureSensor: 'nsu=' + NS + ';i=351',
   ShuttleConveyorType_VibrationSensor: 'nsu=' + NS + ';i=362',
   ShiploaderType_LoadSensor: 'nsu=' + NS + ';i=374',
   ShiploaderType_SpeedSensor: 'nsu=' + NS + ';i=383',
   ShiploaderType_MotorCurrentSensor: 'nsu=' + NS + ';i=392',
   ShiploaderType_MotorVoltageSensor: 'nsu=' + NS + ';i=401',
   ShiploaderType_OperatingStateSensor: 'nsu=' + NS + ';i=410',
   ShiploaderType_MotorTemperatureSensor: 'nsu=' + NS + ';i=419',
   ShiploaderType_VibrationSensor: 'nsu=' + NS + ';i=429',
   AutomaticSamplerType_SamplingArmPositionSensor: 'nsu=' + NS + ';i=442',
   AutomaticSamplerType_MotorCurrentSensor: 'nsu=' + NS + ';i=451',
   AutomaticSamplerType_MotorVoltageSensor: 'nsu=' + NS + ';i=460',
   AutomaticSamplerType_OperatingStateSensor: 'nsu=' + NS + ';i=469',
   AutomaticSamplerType_MotorTemperatureSensor: 'nsu=' + NS + ';i=478',
   AutomaticSamplerType_VibrationSensor: 'nsu=' + NS + ';i=488',
   QualityIdentifierType_MotorCurrentSensor: 'nsu=' + NS + ';i=501',
   QualityIdentifierType_MotorVoltageSensor: 'nsu=' + NS + ';i=510',
   QualityIdentifierType_OperatingStateSensor: 'nsu=' + NS + ';i=519',
   QualityIdentifierType_MotorTemperatureSensor: 'nsu=' + NS + ';i=528',
   QualityIdentifierType_VibrationSensor: 'nsu=' + NS + ';i=538',
   ScreeningUnitType_MotorCurrentSensor: 'nsu=' + NS + ';i=550',
   ScreeningUnitType_MotorVoltageSensor: 'nsu=' + NS + ';i=559',
   ScreeningUnitType_OperatingStateSensor: 'nsu=' + NS + ';i=568',
   ScreeningUnitType_MotorTemperatureSensor: 'nsu=' + NS + ';i=577',
   ScreeningUnitType_VibrationSensor: 'nsu=' + NS + ';i=587',
   ScreeningUnitType_ScreenThicknessSensor: 'nsu=' + NS + ';i=598',
   StorageHall1: 'nsu=' + NS + ';i=607',
   StorageHall1_HumiditySensor: 'nsu=' + NS + ';i=610',
   StorageHall1_DustConcentrationSensor: 'nsu=' + NS + ';i=622',
   TripperCar1: 'nsu=' + NS + ';i=631',
   TripperCar1_Identification: 'nsu=' + NS + ';i=632',
   TripperCar1_SpeedSensor: 'nsu=' + NS + ';i=645',
   TripperCar1_MotorCurrentSensor: 'nsu=' + NS + ';i=654',
   TripperCar1_MotorVoltageSensor: 'nsu=' + NS + ';i=663',
   TripperCar1_OperatingStateSensor: 'nsu=' + NS + ';i=672',
   TripperCar1_MotorTemperatureSensor: 'nsu=' + NS + ';i=681',
   TripperCar1_PositionSensor: 'nsu=' + NS + ';i=690',
   TripperCar1_VibrationSensor: 'nsu=' + NS + ';i=700',
   AutomaticSampler1: 'nsu=' + NS + ';i=711',
   AutomaticSampler1_Identification: 'nsu=' + NS + ';i=712',
   AutomaticSampler1_SamplingArmPositionSensor: 'nsu=' + NS + ';i=721',
   AutomaticSampler1_MotorCurrentSensor: 'nsu=' + NS + ';i=730',
   AutomaticSampler1_MotorVoltageSensor: 'nsu=' + NS + ';i=739',
   AutomaticSampler1_OperatingStateSensor: 'nsu=' + NS + ';i=748',
   AutomaticSampler1_MotorTemperatureSensor: 'nsu=' + NS + ';i=757',
   AutomaticSampler1_VibrationSensor: 'nsu=' + NS + ';i=767',
   QualityIdentifier1: 'nsu=' + NS + ';i=778',
   QualityIdentifier1_Identification: 'nsu=' + NS + ';i=779',
   QualityIdentifier1_MotorCurrentSensor: 'nsu=' + NS + ';i=788',
   QualityIdentifier1_MotorVoltageSensor: 'nsu=' + NS + ';i=797',
   QualityIdentifier1_OperatingStateSensor: 'nsu=' + NS + ';i=806',
   QualityIdentifier1_MotorTemperatureSensor: 'nsu=' + NS + ';i=815',
   QualityIdentifier1_VibrationSensor: 'nsu=' + NS + ';i=825',
   ScreeningUnit1: 'nsu=' + NS + ';i=836',
   ScreeningUnit1_Identification: 'nsu=' + NS + ';i=837',
   ScreeningUnit1_MotorCurrentSensor: 'nsu=' + NS + ';i=845',
   ScreeningUnit1_MotorVoltageSensor: 'nsu=' + NS + ';i=854',
   ScreeningUnit1_OperatingStateSensor: 'nsu=' + NS + ';i=863',
   ScreeningUnit1_MotorTemperatureSensor: 'nsu=' + NS + ';i=872',
   ScreeningUnit1_VibrationSensor: 'nsu=' + NS + ';i=882',
   ScreeningUnit1_ScreenThicknessSensor: 'nsu=' + NS + ';i=893',
   Shiploader1: 'nsu=' + NS + ';i=902',
   Shiploader1_Identification: 'nsu=' + NS + ';i=903',
   Shiploader1_LoadSensor: 'nsu=' + NS + ';i=916',
   Shiploader1_SpeedSensor: 'nsu=' + NS + ';i=925',
   Shiploader1_MotorCurrentSensor: 'nsu=' + NS + ';i=934',
   Shiploader1_MotorVoltageSensor: 'nsu=' + NS + ';i=943',
   Shiploader1_OperatingStateSensor: 'nsu=' + NS + ';i=952',
   Shiploader1_MotorTemperatureSensor: 'nsu=' + NS + ';i=961',
   Shiploader1_VibrationSensor: 'nsu=' + NS + ';i=971',
   ShuttleConveyor1: 'nsu=' + NS + ';i=982',
   ShuttleConveyor1_Identification: 'nsu=' + NS + ';i=983',
   ShuttleConveyor1_LoadingStateSensor: 'nsu=' + NS + ';i=993',
   ShuttleConveyor1_BeltLoadSensor: 'nsu=' + NS + ';i=1002',
   ShuttleConveyor1_MotorCurrentSensor: 'nsu=' + NS + ';i=1011',
   ShuttleConveyor1_MotorVoltageSensor: 'nsu=' + NS + ';i=1020',
   ShuttleConveyor1_OperatingStateSensor: 'nsu=' + NS + ';i=1029',
   ShuttleConveyor1_MotorTemperatureSensor: 'nsu=' + NS + ';i=1038',
   ShuttleConveyor1_VibrationSensor: 'nsu=' + NS + ';i=1049',
   Scraper1: 'nsu=' + NS + ';i=1060',
   Scraper1_Identification: 'nsu=' + NS + ';i=1061',
   Scraper1_SpeedSensor: 'nsu=' + NS + ';i=1074',
   Scraper1_MotorCurrentSensor: 'nsu=' + NS + ';i=1083',
   Scraper1_MotorVoltageSensor: 'nsu=' + NS + ';i=1092',
   Scraper1_OperatingStateSensor: 'nsu=' + NS + ';i=1101',
   Scraper1_MotorTemperatureSensor: 'nsu=' + NS + ';i=1110',
   Scraper1_PositionSensor: 'nsu=' + NS + ';i=1119',
   Scraper1_VibrationSensor: 'nsu=' + NS + ';i=1129',
   BeltConveyor1: 'nsu=' + NS + ';i=1140',
   BeltConveyor1_Identification: 'nsu=' + NS + ';i=1141',
   BeltConveyor1_BeltSpeedSensor: 'nsu=' + NS + ';i=1151',
   BeltConveyor1_VolumeFlowRateSensor: 'nsu=' + NS + ';i=1160',
   BeltConveyor1_BeltLoadSensor: 'nsu=' + NS + ';i=1169',
   BeltConveyor1_MotorCurrentSensor: 'nsu=' + NS + ';i=1178',
   BeltConveyor1_MotorVoltageSensor: 'nsu=' + NS + ';i=1187',
   BeltConveyor1_OperatingStateSensor: 'nsu=' + NS + ';i=1196',
   BeltConveyor1_MotorTemperatureSensor: 'nsu=' + NS + ';i=1205',
   BeltConveyor1_VibrationSensor: 'nsu=' + NS + ';i=1215',
   BeltConveyor1_BeltAlignmentSensor: 'nsu=' + NS + ';i=1226',
});

export const ObjectTypeIds = Object.freeze({
   SensorType: 'nsu=' + NS + ';i=5',
   SpeedSensorType: 'nsu=' + NS + ';i=14',
   PositionSensorType: 'nsu=' + NS + ';i=15',
   TemperatureSensorType: 'nsu=' + NS + ';i=16',
   VibrationSensorType: 'nsu=' + NS + ';i=17',
   HumiditySensorType: 'nsu=' + NS + ';i=20',
   DustConcentrationSensorType: 'nsu=' + NS + ';i=21',
   LoadSensorType: 'nsu=' + NS + ';i=22',
   VolumeFlowRateSensorType: 'nsu=' + NS + ';i=23',
   AlignmentSensorType: 'nsu=' + NS + ';i=24',
   LevelSensorType: 'nsu=' + NS + ';i=25',
   CurrentSensorType: 'nsu=' + NS + ';i=26',
   VoltageSensorType: 'nsu=' + NS + ';i=27',
   WearSensorType: 'nsu=' + NS + ';i=28',
   StateSensorType: 'nsu=' + NS + ';i=29',
   MiningEquipmentIdentificationType: 'nsu=' + NS + ';i=36',
   MiningEquipmentType: 'nsu=' + NS + ';i=44',
   LoadingMachineType: 'nsu=' + NS + ';i=53',
   ScraperType: 'nsu=' + NS + ';i=59',
   StorageHallType: 'nsu=' + NS + ';i=126',
   TripperCarType: 'nsu=' + NS + ';i=150',
   ConveyorMachineType: 'nsu=' + NS + ';i=217',
   BeltConveyorType: 'nsu=' + NS + ';i=220',
   ShuttleConveyorType: 'nsu=' + NS + ';i=305',
   ShiploaderType: 'nsu=' + NS + ';i=373',
   AutomaticSamplerType: 'nsu=' + NS + ';i=440',
   QualityIdentifierType: 'nsu=' + NS + ';i=499',
   ScreeningUnitType: 'nsu=' + NS + ';i=549',
});

export const VariableIds = Object.freeze({
   StructuredArrayItemType_EngineeringUnits: 'nsu=' + NS + ';i=2',
   StructuredArrayItemType_EURange: 'nsu=' + NS + ';i=3',
   StructuredArrayItemType_InstrumentRange: 'nsu=' + NS + ';i=4',
   SensorType_Measurement: 'nsu=' + NS + ';i=6',
   SensorType_Measurement_EURange: 'nsu=' + NS + ';i=10',
   SensorType_EngineeringUnits: 'nsu=' + NS + ';i=12',
   SensorType_EURange: 'nsu=' + NS + ';i=13',
   VibrationSensorType_Frequency: 'nsu=' + NS + ';i=18',
   VibrationSensorType_Amplitude: 'nsu=' + NS + ';i=19',
   StateSensorType_Measurement: 'nsu=' + NS + ';i=30',
   StateSensorType_Measurement_EURange: 'nsu=' + NS + ';i=34',
   MiningEquipmentIdentificationType_AssetId: 'nsu=' + NS + ';i=37',
   MiningEquipmentIdentificationType_DeviceClass: 'nsu=' + NS + ';i=38',
   MiningEquipmentIdentificationType_Manufacturer: 'nsu=' + NS + ';i=39',
   MiningEquipmentIdentificationType_ManufacturerUri: 'nsu=' + NS + ';i=40',
   MiningEquipmentIdentificationType_Model: 'nsu=' + NS + ';i=41',
   MiningEquipmentIdentificationType_ProductInstanceUri: 'nsu=' + NS + ';i=42',
   MiningEquipmentIdentificationType_SerialNumber: 'nsu=' + NS + ';i=43',
   MiningEquipmentType_Identification_AssetId: 'nsu=' + NS + ';i=46',
   MiningEquipmentType_Identification_DeviceClass: 'nsu=' + NS + ';i=47',
   MiningEquipmentType_Identification_Manufacturer: 'nsu=' + NS + ';i=48',
   MiningEquipmentType_Identification_ManufacturerUri: 'nsu=' + NS + ';i=49',
   MiningEquipmentType_Identification_Model: 'nsu=' + NS + ';i=50',
   MiningEquipmentType_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=51',
   MiningEquipmentType_Identification_SerialNumber: 'nsu=' + NS + ';i=52',
   LoadingMachineType_ExclusionZone: 'nsu=' + NS + ';i=57',
   LoadingMachineType_MachinePose: 'nsu=' + NS + ';i=58',
   ScraperType_SpeedSensor_Measurement: 'nsu=' + NS + ';i=61',
   ScraperType_SpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=65',
   ScraperType_SpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=67',
   ScraperType_SpeedSensor_EURange: 'nsu=' + NS + ';i=68',
   ScraperType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=70',
   ScraperType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=74',
   ScraperType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=76',
   ScraperType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=77',
   ScraperType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=79',
   ScraperType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=83',
   ScraperType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=85',
   ScraperType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=86',
   ScraperType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=88',
   ScraperType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=92',
   ScraperType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=94',
   ScraperType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=95',
   ScraperType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=97',
   ScraperType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=101',
   ScraperType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=103',
   ScraperType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=104',
   ScraperType_PositionSensor_Measurement: 'nsu=' + NS + ';i=106',
   ScraperType_PositionSensor_Measurement_EURange: 'nsu=' + NS + ';i=110',
   ScraperType_PositionSensor_EngineeringUnits: 'nsu=' + NS + ';i=112',
   ScraperType_PositionSensor_EURange: 'nsu=' + NS + ';i=113',
   ScraperType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=114',
   ScraperType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=116',
   ScraperType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=120',
   ScraperType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=122',
   ScraperType_VibrationSensor_EURange: 'nsu=' + NS + ';i=123',
   ScraperType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=124',
   ScraperType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=125',
   StorageHallType_StockpileCoordinates: 'nsu=' + NS + ';i=127',
   StorageHallType_DistanceBetweenStockpiles: 'nsu=' + NS + ';i=128',
   StorageHallType_HumiditySensor_Measurement: 'nsu=' + NS + ';i=130',
   StorageHallType_HumiditySensor_Measurement_EURange: 'nsu=' + NS + ';i=134',
   StorageHallType_HumiditySensor_EngineeringUnits: 'nsu=' + NS + ';i=136',
   StorageHallType_HumiditySensor_EURange: 'nsu=' + NS + ';i=137',
   StorageHallType_FillingRate: 'nsu=' + NS + ';i=138',
   StorageHallType_StockpileHeight: 'nsu=' + NS + ';i=139',
   StorageHallType_StockpileColor: 'nsu=' + NS + ';i=140',
   StorageHallType_DustConcentrationSensor_Measurement: 'nsu=' + NS + ';i=142',
   StorageHallType_DustConcentrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=146',
   StorageHallType_DustConcentrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=148',
   StorageHallType_DustConcentrationSensor_EURange: 'nsu=' + NS + ';i=149',
   TripperCarType_SpeedSensor_Measurement: 'nsu=' + NS + ';i=152',
   TripperCarType_SpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=156',
   TripperCarType_SpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=158',
   TripperCarType_SpeedSensor_EURange: 'nsu=' + NS + ';i=159',
   TripperCarType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=161',
   TripperCarType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=165',
   TripperCarType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=167',
   TripperCarType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=168',
   TripperCarType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=170',
   TripperCarType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=174',
   TripperCarType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=176',
   TripperCarType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=177',
   TripperCarType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=179',
   TripperCarType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=183',
   TripperCarType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=185',
   TripperCarType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=186',
   TripperCarType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=188',
   TripperCarType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=192',
   TripperCarType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=194',
   TripperCarType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=195',
   TripperCarType_PositionSensor_Measurement: 'nsu=' + NS + ';i=197',
   TripperCarType_PositionSensor_Measurement_EURange: 'nsu=' + NS + ';i=201',
   TripperCarType_PositionSensor_EngineeringUnits: 'nsu=' + NS + ';i=203',
   TripperCarType_PositionSensor_EURange: 'nsu=' + NS + ';i=204',
   TripperCarType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=205',
   TripperCarType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=207',
   TripperCarType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=211',
   TripperCarType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=213',
   TripperCarType_VibrationSensor_EURange: 'nsu=' + NS + ';i=214',
   TripperCarType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=215',
   TripperCarType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=216',
   BeltConveyorType_BeltSpeedSensor_Measurement: 'nsu=' + NS + ';i=222',
   BeltConveyorType_BeltSpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=226',
   BeltConveyorType_BeltSpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=228',
   BeltConveyorType_BeltSpeedSensor_EURange: 'nsu=' + NS + ';i=229',
   BeltConveyorType_VolumeFlowRateSensor_Measurement: 'nsu=' + NS + ';i=231',
   BeltConveyorType_VolumeFlowRateSensor_Measurement_EURange: 'nsu=' + NS + ';i=235',
   BeltConveyorType_VolumeFlowRateSensor_EngineeringUnits: 'nsu=' + NS + ';i=237',
   BeltConveyorType_VolumeFlowRateSensor_EURange: 'nsu=' + NS + ';i=238',
   BeltConveyorType_BeltLoadSensor_Measurement: 'nsu=' + NS + ';i=240',
   BeltConveyorType_BeltLoadSensor_Measurement_EURange: 'nsu=' + NS + ';i=244',
   BeltConveyorType_BeltLoadSensor_EngineeringUnits: 'nsu=' + NS + ';i=246',
   BeltConveyorType_BeltLoadSensor_EURange: 'nsu=' + NS + ';i=247',
   BeltConveyorType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=249',
   BeltConveyorType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=253',
   BeltConveyorType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=255',
   BeltConveyorType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=256',
   BeltConveyorType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=258',
   BeltConveyorType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=262',
   BeltConveyorType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=264',
   BeltConveyorType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=265',
   BeltConveyorType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=267',
   BeltConveyorType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=271',
   BeltConveyorType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=273',
   BeltConveyorType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=274',
   BeltConveyorType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=276',
   BeltConveyorType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=280',
   BeltConveyorType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=282',
   BeltConveyorType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=283',
   BeltConveyorType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=284',
   BeltConveyorType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=286',
   BeltConveyorType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=290',
   BeltConveyorType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=292',
   BeltConveyorType_VibrationSensor_EURange: 'nsu=' + NS + ';i=293',
   BeltConveyorType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=294',
   BeltConveyorType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=295',
   BeltConveyorType_BeltAlignmentSensor_Measurement: 'nsu=' + NS + ';i=297',
   BeltConveyorType_BeltAlignmentSensor_Measurement_EURange: 'nsu=' + NS + ';i=301',
   BeltConveyorType_BeltAlignmentSensor_EngineeringUnits: 'nsu=' + NS + ';i=303',
   BeltConveyorType_BeltAlignmentSensor_EURange: 'nsu=' + NS + ';i=304',
   ShuttleConveyorType_LoadingStateSensor_Measurement: 'nsu=' + NS + ';i=307',
   ShuttleConveyorType_LoadingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=311',
   ShuttleConveyorType_LoadingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=313',
   ShuttleConveyorType_LoadingStateSensor_EURange: 'nsu=' + NS + ';i=314',
   ShuttleConveyorType_BeltLoadSensor_Measurement: 'nsu=' + NS + ';i=316',
   ShuttleConveyorType_BeltLoadSensor_Measurement_EURange: 'nsu=' + NS + ';i=320',
   ShuttleConveyorType_BeltLoadSensor_EngineeringUnits: 'nsu=' + NS + ';i=322',
   ShuttleConveyorType_BeltLoadSensor_EURange: 'nsu=' + NS + ';i=323',
   ShuttleConveyorType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=325',
   ShuttleConveyorType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=329',
   ShuttleConveyorType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=331',
   ShuttleConveyorType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=332',
   ShuttleConveyorType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=334',
   ShuttleConveyorType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=338',
   ShuttleConveyorType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=340',
   ShuttleConveyorType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=341',
   ShuttleConveyorType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=343',
   ShuttleConveyorType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=347',
   ShuttleConveyorType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=349',
   ShuttleConveyorType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=350',
   ShuttleConveyorType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=352',
   ShuttleConveyorType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=356',
   ShuttleConveyorType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=358',
   ShuttleConveyorType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=359',
   ShuttleConveyorType_DirectionSignal: 'nsu=' + NS + ';i=360',
   ShuttleConveyorType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=361',
   ShuttleConveyorType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=363',
   ShuttleConveyorType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=367',
   ShuttleConveyorType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=369',
   ShuttleConveyorType_VibrationSensor_EURange: 'nsu=' + NS + ';i=370',
   ShuttleConveyorType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=371',
   ShuttleConveyorType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=372',
   ShiploaderType_LoadSensor_Measurement: 'nsu=' + NS + ';i=375',
   ShiploaderType_LoadSensor_Measurement_EURange: 'nsu=' + NS + ';i=379',
   ShiploaderType_LoadSensor_EngineeringUnits: 'nsu=' + NS + ';i=381',
   ShiploaderType_LoadSensor_EURange: 'nsu=' + NS + ';i=382',
   ShiploaderType_SpeedSensor_Measurement: 'nsu=' + NS + ';i=384',
   ShiploaderType_SpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=388',
   ShiploaderType_SpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=390',
   ShiploaderType_SpeedSensor_EURange: 'nsu=' + NS + ';i=391',
   ShiploaderType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=393',
   ShiploaderType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=397',
   ShiploaderType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=399',
   ShiploaderType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=400',
   ShiploaderType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=402',
   ShiploaderType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=406',
   ShiploaderType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=408',
   ShiploaderType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=409',
   ShiploaderType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=411',
   ShiploaderType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=415',
   ShiploaderType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=417',
   ShiploaderType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=418',
   ShiploaderType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=420',
   ShiploaderType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=424',
   ShiploaderType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=426',
   ShiploaderType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=427',
   ShiploaderType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=428',
   ShiploaderType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=430',
   ShiploaderType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=434',
   ShiploaderType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=436',
   ShiploaderType_VibrationSensor_EURange: 'nsu=' + NS + ';i=437',
   ShiploaderType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=438',
   ShiploaderType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=439',
   AutomaticSamplerType_SamplingFrequency: 'nsu=' + NS + ';i=441',
   AutomaticSamplerType_SamplingArmPositionSensor_Measurement: 'nsu=' + NS + ';i=443',
   AutomaticSamplerType_SamplingArmPositionSensor_Measurement_EURange: 'nsu=' + NS + ';i=447',
   AutomaticSamplerType_SamplingArmPositionSensor_EngineeringUnits: 'nsu=' + NS + ';i=449',
   AutomaticSamplerType_SamplingArmPositionSensor_EURange: 'nsu=' + NS + ';i=450',
   AutomaticSamplerType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=452',
   AutomaticSamplerType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=456',
   AutomaticSamplerType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=458',
   AutomaticSamplerType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=459',
   AutomaticSamplerType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=461',
   AutomaticSamplerType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=465',
   AutomaticSamplerType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=467',
   AutomaticSamplerType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=468',
   AutomaticSamplerType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=470',
   AutomaticSamplerType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=474',
   AutomaticSamplerType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=476',
   AutomaticSamplerType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=477',
   AutomaticSamplerType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=479',
   AutomaticSamplerType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=483',
   AutomaticSamplerType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=485',
   AutomaticSamplerType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=486',
   AutomaticSamplerType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=487',
   AutomaticSamplerType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=489',
   AutomaticSamplerType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=493',
   AutomaticSamplerType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=495',
   AutomaticSamplerType_VibrationSensor_EURange: 'nsu=' + NS + ';i=496',
   AutomaticSamplerType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=497',
   AutomaticSamplerType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=498',
   QualityIdentifierType_EmissionSpectrum: 'nsu=' + NS + ';i=500',
   QualityIdentifierType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=502',
   QualityIdentifierType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=506',
   QualityIdentifierType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=508',
   QualityIdentifierType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=509',
   QualityIdentifierType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=511',
   QualityIdentifierType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=515',
   QualityIdentifierType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=517',
   QualityIdentifierType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=518',
   QualityIdentifierType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=520',
   QualityIdentifierType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=524',
   QualityIdentifierType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=526',
   QualityIdentifierType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=527',
   QualityIdentifierType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=529',
   QualityIdentifierType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=533',
   QualityIdentifierType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=535',
   QualityIdentifierType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=536',
   QualityIdentifierType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=537',
   QualityIdentifierType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=539',
   QualityIdentifierType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=543',
   QualityIdentifierType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=545',
   QualityIdentifierType_VibrationSensor_EURange: 'nsu=' + NS + ';i=546',
   QualityIdentifierType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=547',
   QualityIdentifierType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=548',
   ScreeningUnitType_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=551',
   ScreeningUnitType_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=555',
   ScreeningUnitType_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=557',
   ScreeningUnitType_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=558',
   ScreeningUnitType_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=560',
   ScreeningUnitType_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=564',
   ScreeningUnitType_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=566',
   ScreeningUnitType_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=567',
   ScreeningUnitType_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=569',
   ScreeningUnitType_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=573',
   ScreeningUnitType_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=575',
   ScreeningUnitType_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=576',
   ScreeningUnitType_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=578',
   ScreeningUnitType_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=582',
   ScreeningUnitType_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=584',
   ScreeningUnitType_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=585',
   ScreeningUnitType_CumulativeEnergyUsed: 'nsu=' + NS + ';i=586',
   ScreeningUnitType_VibrationSensor_Measurement: 'nsu=' + NS + ';i=588',
   ScreeningUnitType_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=592',
   ScreeningUnitType_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=594',
   ScreeningUnitType_VibrationSensor_EURange: 'nsu=' + NS + ';i=595',
   ScreeningUnitType_VibrationSensor_Frequency: 'nsu=' + NS + ';i=596',
   ScreeningUnitType_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=597',
   ScreeningUnitType_ScreenThicknessSensor_Measurement: 'nsu=' + NS + ';i=599',
   ScreeningUnitType_ScreenThicknessSensor_Measurement_EURange: 'nsu=' + NS + ';i=603',
   ScreeningUnitType_ScreenThicknessSensor_EngineeringUnits: 'nsu=' + NS + ';i=605',
   ScreeningUnitType_ScreenThicknessSensor_EURange: 'nsu=' + NS + ';i=606',
   StorageHall1_StockpileCoordinates: 'nsu=' + NS + ';i=608',
   StorageHall1_DistanceBetweenStockpiles: 'nsu=' + NS + ';i=609',
   StorageHall1_HumiditySensor_Measurement: 'nsu=' + NS + ';i=611',
   StorageHall1_HumiditySensor_Measurement_EURange: 'nsu=' + NS + ';i=615',
   StorageHall1_HumiditySensor_EngineeringUnits: 'nsu=' + NS + ';i=617',
   StorageHall1_HumiditySensor_EURange: 'nsu=' + NS + ';i=618',
   StorageHall1_FillingRate: 'nsu=' + NS + ';i=619',
   StorageHall1_StockpileHeight: 'nsu=' + NS + ';i=620',
   StorageHall1_StockpileColor: 'nsu=' + NS + ';i=621',
   StorageHall1_DustConcentrationSensor_Measurement: 'nsu=' + NS + ';i=623',
   StorageHall1_DustConcentrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=627',
   StorageHall1_DustConcentrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=629',
   StorageHall1_DustConcentrationSensor_EURange: 'nsu=' + NS + ';i=630',
   TripperCar1_Identification_AssetId: 'nsu=' + NS + ';i=633',
   TripperCar1_Identification_DeviceClass: 'nsu=' + NS + ';i=634',
   TripperCar1_Identification_Manufacturer: 'nsu=' + NS + ';i=635',
   TripperCar1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=636',
   TripperCar1_Identification_Model: 'nsu=' + NS + ';i=637',
   TripperCar1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=638',
   TripperCar1_Identification_SerialNumber: 'nsu=' + NS + ';i=639',
   TripperCar1_ExclusionZone: 'nsu=' + NS + ';i=643',
   TripperCar1_MachinePose: 'nsu=' + NS + ';i=644',
   TripperCar1_SpeedSensor_Measurement: 'nsu=' + NS + ';i=646',
   TripperCar1_SpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=650',
   TripperCar1_SpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=652',
   TripperCar1_SpeedSensor_EURange: 'nsu=' + NS + ';i=653',
   TripperCar1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=655',
   TripperCar1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=659',
   TripperCar1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=661',
   TripperCar1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=662',
   TripperCar1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=664',
   TripperCar1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=668',
   TripperCar1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=670',
   TripperCar1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=671',
   TripperCar1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=673',
   TripperCar1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=677',
   TripperCar1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=679',
   TripperCar1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=680',
   TripperCar1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=682',
   TripperCar1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=686',
   TripperCar1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=688',
   TripperCar1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=689',
   TripperCar1_PositionSensor_Measurement: 'nsu=' + NS + ';i=691',
   TripperCar1_PositionSensor_Measurement_EURange: 'nsu=' + NS + ';i=695',
   TripperCar1_PositionSensor_EngineeringUnits: 'nsu=' + NS + ';i=697',
   TripperCar1_PositionSensor_EURange: 'nsu=' + NS + ';i=698',
   TripperCar1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=699',
   TripperCar1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=701',
   TripperCar1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=705',
   TripperCar1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=707',
   TripperCar1_VibrationSensor_EURange: 'nsu=' + NS + ';i=708',
   TripperCar1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=709',
   TripperCar1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=710',
   AutomaticSampler1_Identification_AssetId: 'nsu=' + NS + ';i=713',
   AutomaticSampler1_Identification_DeviceClass: 'nsu=' + NS + ';i=714',
   AutomaticSampler1_Identification_Manufacturer: 'nsu=' + NS + ';i=715',
   AutomaticSampler1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=716',
   AutomaticSampler1_Identification_Model: 'nsu=' + NS + ';i=717',
   AutomaticSampler1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=718',
   AutomaticSampler1_Identification_SerialNumber: 'nsu=' + NS + ';i=719',
   AutomaticSampler1_SamplingFrequency: 'nsu=' + NS + ';i=720',
   AutomaticSampler1_SamplingArmPositionSensor_Measurement: 'nsu=' + NS + ';i=722',
   AutomaticSampler1_SamplingArmPositionSensor_Measurement_EURange: 'nsu=' + NS + ';i=726',
   AutomaticSampler1_SamplingArmPositionSensor_EngineeringUnits: 'nsu=' + NS + ';i=728',
   AutomaticSampler1_SamplingArmPositionSensor_EURange: 'nsu=' + NS + ';i=729',
   AutomaticSampler1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=731',
   AutomaticSampler1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=735',
   AutomaticSampler1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=737',
   AutomaticSampler1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=738',
   AutomaticSampler1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=740',
   AutomaticSampler1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=744',
   AutomaticSampler1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=746',
   AutomaticSampler1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=747',
   AutomaticSampler1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=749',
   AutomaticSampler1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=753',
   AutomaticSampler1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=755',
   AutomaticSampler1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=756',
   AutomaticSampler1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=758',
   AutomaticSampler1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=762',
   AutomaticSampler1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=764',
   AutomaticSampler1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=765',
   AutomaticSampler1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=766',
   AutomaticSampler1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=768',
   AutomaticSampler1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=772',
   AutomaticSampler1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=774',
   AutomaticSampler1_VibrationSensor_EURange: 'nsu=' + NS + ';i=775',
   AutomaticSampler1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=776',
   AutomaticSampler1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=777',
   QualityIdentifier1_Identification_AssetId: 'nsu=' + NS + ';i=780',
   QualityIdentifier1_Identification_DeviceClass: 'nsu=' + NS + ';i=781',
   QualityIdentifier1_Identification_Manufacturer: 'nsu=' + NS + ';i=782',
   QualityIdentifier1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=783',
   QualityIdentifier1_Identification_Model: 'nsu=' + NS + ';i=784',
   QualityIdentifier1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=785',
   QualityIdentifier1_Identification_SerialNumber: 'nsu=' + NS + ';i=786',
   QualityIdentifier1_EmissionSpectrum: 'nsu=' + NS + ';i=787',
   QualityIdentifier1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=789',
   QualityIdentifier1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=793',
   QualityIdentifier1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=795',
   QualityIdentifier1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=796',
   QualityIdentifier1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=798',
   QualityIdentifier1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=802',
   QualityIdentifier1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=804',
   QualityIdentifier1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=805',
   QualityIdentifier1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=807',
   QualityIdentifier1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=811',
   QualityIdentifier1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=813',
   QualityIdentifier1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=814',
   QualityIdentifier1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=816',
   QualityIdentifier1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=820',
   QualityIdentifier1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=822',
   QualityIdentifier1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=823',
   QualityIdentifier1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=824',
   QualityIdentifier1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=826',
   QualityIdentifier1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=830',
   QualityIdentifier1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=832',
   QualityIdentifier1_VibrationSensor_EURange: 'nsu=' + NS + ';i=833',
   QualityIdentifier1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=834',
   QualityIdentifier1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=835',
   ScreeningUnit1_Identification_AssetId: 'nsu=' + NS + ';i=838',
   ScreeningUnit1_Identification_DeviceClass: 'nsu=' + NS + ';i=839',
   ScreeningUnit1_Identification_Manufacturer: 'nsu=' + NS + ';i=840',
   ScreeningUnit1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=841',
   ScreeningUnit1_Identification_Model: 'nsu=' + NS + ';i=842',
   ScreeningUnit1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=843',
   ScreeningUnit1_Identification_SerialNumber: 'nsu=' + NS + ';i=844',
   ScreeningUnit1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=846',
   ScreeningUnit1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=850',
   ScreeningUnit1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=852',
   ScreeningUnit1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=853',
   ScreeningUnit1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=855',
   ScreeningUnit1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=859',
   ScreeningUnit1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=861',
   ScreeningUnit1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=862',
   ScreeningUnit1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=864',
   ScreeningUnit1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=868',
   ScreeningUnit1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=870',
   ScreeningUnit1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=871',
   ScreeningUnit1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=873',
   ScreeningUnit1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=877',
   ScreeningUnit1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=879',
   ScreeningUnit1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=880',
   ScreeningUnit1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=881',
   ScreeningUnit1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=883',
   ScreeningUnit1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=887',
   ScreeningUnit1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=889',
   ScreeningUnit1_VibrationSensor_EURange: 'nsu=' + NS + ';i=890',
   ScreeningUnit1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=891',
   ScreeningUnit1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=892',
   ScreeningUnit1_ScreenThicknessSensor_Measurement: 'nsu=' + NS + ';i=894',
   ScreeningUnit1_ScreenThicknessSensor_Measurement_EURange: 'nsu=' + NS + ';i=898',
   ScreeningUnit1_ScreenThicknessSensor_EngineeringUnits: 'nsu=' + NS + ';i=900',
   ScreeningUnit1_ScreenThicknessSensor_EURange: 'nsu=' + NS + ';i=901',
   Shiploader1_Identification_AssetId: 'nsu=' + NS + ';i=904',
   Shiploader1_Identification_DeviceClass: 'nsu=' + NS + ';i=905',
   Shiploader1_Identification_Manufacturer: 'nsu=' + NS + ';i=906',
   Shiploader1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=907',
   Shiploader1_Identification_Model: 'nsu=' + NS + ';i=908',
   Shiploader1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=909',
   Shiploader1_Identification_SerialNumber: 'nsu=' + NS + ';i=910',
   Shiploader1_ExclusionZone: 'nsu=' + NS + ';i=914',
   Shiploader1_MachinePose: 'nsu=' + NS + ';i=915',
   Shiploader1_LoadSensor_Measurement: 'nsu=' + NS + ';i=917',
   Shiploader1_LoadSensor_Measurement_EURange: 'nsu=' + NS + ';i=921',
   Shiploader1_LoadSensor_EngineeringUnits: 'nsu=' + NS + ';i=923',
   Shiploader1_LoadSensor_EURange: 'nsu=' + NS + ';i=924',
   Shiploader1_SpeedSensor_Measurement: 'nsu=' + NS + ';i=926',
   Shiploader1_SpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=930',
   Shiploader1_SpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=932',
   Shiploader1_SpeedSensor_EURange: 'nsu=' + NS + ';i=933',
   Shiploader1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=935',
   Shiploader1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=939',
   Shiploader1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=941',
   Shiploader1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=942',
   Shiploader1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=944',
   Shiploader1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=948',
   Shiploader1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=950',
   Shiploader1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=951',
   Shiploader1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=953',
   Shiploader1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=957',
   Shiploader1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=959',
   Shiploader1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=960',
   Shiploader1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=962',
   Shiploader1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=966',
   Shiploader1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=968',
   Shiploader1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=969',
   Shiploader1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=970',
   Shiploader1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=972',
   Shiploader1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=976',
   Shiploader1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=978',
   Shiploader1_VibrationSensor_EURange: 'nsu=' + NS + ';i=979',
   Shiploader1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=980',
   Shiploader1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=981',
   ShuttleConveyor1_Identification_AssetId: 'nsu=' + NS + ';i=984',
   ShuttleConveyor1_Identification_DeviceClass: 'nsu=' + NS + ';i=985',
   ShuttleConveyor1_Identification_Manufacturer: 'nsu=' + NS + ';i=986',
   ShuttleConveyor1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=987',
   ShuttleConveyor1_Identification_Model: 'nsu=' + NS + ';i=988',
   ShuttleConveyor1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=989',
   ShuttleConveyor1_Identification_SerialNumber: 'nsu=' + NS + ';i=990',
   ShuttleConveyor1_LoadingStateSensor_Measurement: 'nsu=' + NS + ';i=994',
   ShuttleConveyor1_LoadingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=998',
   ShuttleConveyor1_LoadingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=1000',
   ShuttleConveyor1_LoadingStateSensor_EURange: 'nsu=' + NS + ';i=1001',
   ShuttleConveyor1_BeltLoadSensor_Measurement: 'nsu=' + NS + ';i=1003',
   ShuttleConveyor1_BeltLoadSensor_Measurement_EURange: 'nsu=' + NS + ';i=1007',
   ShuttleConveyor1_BeltLoadSensor_EngineeringUnits: 'nsu=' + NS + ';i=1009',
   ShuttleConveyor1_BeltLoadSensor_EURange: 'nsu=' + NS + ';i=1010',
   ShuttleConveyor1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=1012',
   ShuttleConveyor1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=1016',
   ShuttleConveyor1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=1018',
   ShuttleConveyor1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=1019',
   ShuttleConveyor1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=1021',
   ShuttleConveyor1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=1025',
   ShuttleConveyor1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=1027',
   ShuttleConveyor1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=1028',
   ShuttleConveyor1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=1030',
   ShuttleConveyor1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=1034',
   ShuttleConveyor1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=1036',
   ShuttleConveyor1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=1037',
   ShuttleConveyor1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=1039',
   ShuttleConveyor1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=1043',
   ShuttleConveyor1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=1045',
   ShuttleConveyor1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=1046',
   ShuttleConveyor1_DirectionSignal: 'nsu=' + NS + ';i=1047',
   ShuttleConveyor1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=1048',
   ShuttleConveyor1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=1050',
   ShuttleConveyor1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=1054',
   ShuttleConveyor1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=1056',
   ShuttleConveyor1_VibrationSensor_EURange: 'nsu=' + NS + ';i=1057',
   ShuttleConveyor1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=1058',
   ShuttleConveyor1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=1059',
   Scraper1_Identification_AssetId: 'nsu=' + NS + ';i=1062',
   Scraper1_Identification_DeviceClass: 'nsu=' + NS + ';i=1063',
   Scraper1_Identification_Manufacturer: 'nsu=' + NS + ';i=1064',
   Scraper1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=1065',
   Scraper1_Identification_Model: 'nsu=' + NS + ';i=1066',
   Scraper1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=1067',
   Scraper1_Identification_SerialNumber: 'nsu=' + NS + ';i=1068',
   Scraper1_ExclusionZone: 'nsu=' + NS + ';i=1072',
   Scraper1_MachinePose: 'nsu=' + NS + ';i=1073',
   Scraper1_SpeedSensor_Measurement: 'nsu=' + NS + ';i=1075',
   Scraper1_SpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=1079',
   Scraper1_SpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=1081',
   Scraper1_SpeedSensor_EURange: 'nsu=' + NS + ';i=1082',
   Scraper1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=1084',
   Scraper1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=1088',
   Scraper1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=1090',
   Scraper1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=1091',
   Scraper1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=1093',
   Scraper1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=1097',
   Scraper1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=1099',
   Scraper1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=1100',
   Scraper1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=1102',
   Scraper1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=1106',
   Scraper1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=1108',
   Scraper1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=1109',
   Scraper1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=1111',
   Scraper1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=1115',
   Scraper1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=1117',
   Scraper1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=1118',
   Scraper1_PositionSensor_Measurement: 'nsu=' + NS + ';i=1120',
   Scraper1_PositionSensor_Measurement_EURange: 'nsu=' + NS + ';i=1124',
   Scraper1_PositionSensor_EngineeringUnits: 'nsu=' + NS + ';i=1126',
   Scraper1_PositionSensor_EURange: 'nsu=' + NS + ';i=1127',
   Scraper1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=1128',
   Scraper1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=1130',
   Scraper1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=1134',
   Scraper1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=1136',
   Scraper1_VibrationSensor_EURange: 'nsu=' + NS + ';i=1137',
   Scraper1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=1138',
   Scraper1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=1139',
   BeltConveyor1_Identification_AssetId: 'nsu=' + NS + ';i=1142',
   BeltConveyor1_Identification_DeviceClass: 'nsu=' + NS + ';i=1143',
   BeltConveyor1_Identification_Manufacturer: 'nsu=' + NS + ';i=1144',
   BeltConveyor1_Identification_ManufacturerUri: 'nsu=' + NS + ';i=1145',
   BeltConveyor1_Identification_Model: 'nsu=' + NS + ';i=1146',
   BeltConveyor1_Identification_ProductInstanceUri: 'nsu=' + NS + ';i=1147',
   BeltConveyor1_Identification_SerialNumber: 'nsu=' + NS + ';i=1148',
   BeltConveyor1_BeltSpeedSensor_Measurement: 'nsu=' + NS + ';i=1152',
   BeltConveyor1_BeltSpeedSensor_Measurement_EURange: 'nsu=' + NS + ';i=1156',
   BeltConveyor1_BeltSpeedSensor_EngineeringUnits: 'nsu=' + NS + ';i=1158',
   BeltConveyor1_BeltSpeedSensor_EURange: 'nsu=' + NS + ';i=1159',
   BeltConveyor1_VolumeFlowRateSensor_Measurement: 'nsu=' + NS + ';i=1161',
   BeltConveyor1_VolumeFlowRateSensor_Measurement_EURange: 'nsu=' + NS + ';i=1165',
   BeltConveyor1_VolumeFlowRateSensor_EngineeringUnits: 'nsu=' + NS + ';i=1167',
   BeltConveyor1_VolumeFlowRateSensor_EURange: 'nsu=' + NS + ';i=1168',
   BeltConveyor1_BeltLoadSensor_Measurement: 'nsu=' + NS + ';i=1170',
   BeltConveyor1_BeltLoadSensor_Measurement_EURange: 'nsu=' + NS + ';i=1174',
   BeltConveyor1_BeltLoadSensor_EngineeringUnits: 'nsu=' + NS + ';i=1176',
   BeltConveyor1_BeltLoadSensor_EURange: 'nsu=' + NS + ';i=1177',
   BeltConveyor1_MotorCurrentSensor_Measurement: 'nsu=' + NS + ';i=1179',
   BeltConveyor1_MotorCurrentSensor_Measurement_EURange: 'nsu=' + NS + ';i=1183',
   BeltConveyor1_MotorCurrentSensor_EngineeringUnits: 'nsu=' + NS + ';i=1185',
   BeltConveyor1_MotorCurrentSensor_EURange: 'nsu=' + NS + ';i=1186',
   BeltConveyor1_MotorVoltageSensor_Measurement: 'nsu=' + NS + ';i=1188',
   BeltConveyor1_MotorVoltageSensor_Measurement_EURange: 'nsu=' + NS + ';i=1192',
   BeltConveyor1_MotorVoltageSensor_EngineeringUnits: 'nsu=' + NS + ';i=1194',
   BeltConveyor1_MotorVoltageSensor_EURange: 'nsu=' + NS + ';i=1195',
   BeltConveyor1_OperatingStateSensor_Measurement: 'nsu=' + NS + ';i=1197',
   BeltConveyor1_OperatingStateSensor_Measurement_EURange: 'nsu=' + NS + ';i=1201',
   BeltConveyor1_OperatingStateSensor_EngineeringUnits: 'nsu=' + NS + ';i=1203',
   BeltConveyor1_OperatingStateSensor_EURange: 'nsu=' + NS + ';i=1204',
   BeltConveyor1_MotorTemperatureSensor_Measurement: 'nsu=' + NS + ';i=1206',
   BeltConveyor1_MotorTemperatureSensor_Measurement_EURange: 'nsu=' + NS + ';i=1210',
   BeltConveyor1_MotorTemperatureSensor_EngineeringUnits: 'nsu=' + NS + ';i=1212',
   BeltConveyor1_MotorTemperatureSensor_EURange: 'nsu=' + NS + ';i=1213',
   BeltConveyor1_CumulativeEnergyUsed: 'nsu=' + NS + ';i=1214',
   BeltConveyor1_VibrationSensor_Measurement: 'nsu=' + NS + ';i=1216',
   BeltConveyor1_VibrationSensor_Measurement_EURange: 'nsu=' + NS + ';i=1220',
   BeltConveyor1_VibrationSensor_EngineeringUnits: 'nsu=' + NS + ';i=1222',
   BeltConveyor1_VibrationSensor_EURange: 'nsu=' + NS + ';i=1223',
   BeltConveyor1_VibrationSensor_Frequency: 'nsu=' + NS + ';i=1224',
   BeltConveyor1_VibrationSensor_Amplitude: 'nsu=' + NS + ';i=1225',
   BeltConveyor1_BeltAlignmentSensor_Measurement: 'nsu=' + NS + ';i=1227',
   BeltConveyor1_BeltAlignmentSensor_Measurement_EURange: 'nsu=' + NS + ';i=1231',
   BeltConveyor1_BeltAlignmentSensor_EngineeringUnits: 'nsu=' + NS + ';i=1233',
   BeltConveyor1_BeltAlignmentSensor_EURange: 'nsu=' + NS + ';i=1234',
});

export const VariableTypeIds = Object.freeze({
   StructuredArrayItemType: 'nsu=' + NS + ';i=1',
});
