export const NS = 'http://example.com/StockToPort';

export class BrowseNames {
   static readonly AlignmentSensorType: string = 'AlignmentSensorType'
   static readonly Amplitude: string = 'Amplitude'
   static readonly AssetId: string = 'AssetId'
   static readonly AutomaticSampler1: string = 'Automatic Sampler #1'
   static readonly AutomaticSamplerType: string = 'AutomaticSamplerType'
   static readonly BeltAlignmentSensor: string = 'BeltAlignmentSensor'
   static readonly BeltConveyor1: string = 'Belt Conveyor #1'
   static readonly BeltConveyorType: string = 'BeltConveyorType'
   static readonly BeltLoadSensor: string = 'BeltLoadSensor'
   static readonly BeltSpeedSensor: string = 'BeltSpeedSensor'
   static readonly ConveyorMachineType: string = 'ConveyorMachineType'
   static readonly CumulativeEnergyUsed: string = 'CumulativeEnergyUsed'
   static readonly CurrentSensorType: string = 'CurrentSensorType'
   static readonly DeviceClass: string = 'DeviceClass'
   static readonly DirectionSignal: string = 'DirectionSignal'
   static readonly DistanceBetweenStockpiles: string = 'DistanceBetweenStockpiles'
   static readonly DustConcentrationSensor: string = 'DustConcentrationSensor'
   static readonly DustConcentrationSensorType: string = 'DustConcentrationSensorType'
   static readonly EmissionSpectrum: string = 'EmissionSpectrum'
   static readonly EngineeringUnits: string = 'EngineeringUnits'
   static readonly EURange: string = 'EURange'
   static readonly ExclusionZone: string = 'ExclusionZone'
   static readonly FillingRate: string = 'FillingRate'
   static readonly Frequency: string = 'Frequency'
   static readonly HumiditySensor: string = 'HumiditySensor'
   static readonly HumiditySensorType: string = 'HumiditySensorType'
   static readonly Identification: string = 'Identification'
   static readonly InstrumentRange: string = 'InstrumentRange'
   static readonly LevelSensorType: string = 'LevelSensorType'
   static readonly LoadingMachineType: string = 'LoadingMachineType'
   static readonly LoadingStateSensor: string = 'LoadingStateSensor'
   static readonly LoadSensor: string = 'LoadSensor'
   static readonly LoadSensorType: string = 'LoadSensorType'
   static readonly MachinePose: string = 'MachinePose'
   static readonly Manufacturer: string = 'Manufacturer'
   static readonly ManufacturerUri: string = 'ManufacturerUri'
   static readonly Measurement: string = 'Measurement'
   static readonly MiningEquipmentIdentificationType: string = 'MiningEquipmentIdentificationType'
   static readonly MiningEquipmentType: string = 'MiningEquipmentType'
   static readonly Model: string = 'Model'
   static readonly MotorCurrentSensor: string = 'MotorCurrentSensor'
   static readonly MotorTemperatureSensor: string = 'MotorTemperatureSensor'
   static readonly MotorVoltageSensor: string = 'MotorVoltageSensor'
   static readonly OperatingStateSensor: string = 'OperatingStateSensor'
   static readonly PositioningComplete: string = 'PositioningComplete'
   static readonly PositionSensor: string = 'PositionSensor'
   static readonly PositionSensorType: string = 'PositionSensorType'
   static readonly ProductInstanceUri: string = 'ProductInstanceUri'
   static readonly QualityIdentifier1: string = 'Quality Identifier #1'
   static readonly QualityIdentifierType: string = 'QualityIdentifierType'
   static readonly RequestForLoading: string = 'RequestForLoading'
   static readonly SamplingArmPositionSensor: string = 'SamplingArmPositionSensor'
   static readonly SamplingFrequency: string = 'SamplingFrequency'
   static readonly Scraper1: string = 'Scraper #1'
   static readonly ScraperType: string = 'ScraperType'
   static readonly ScreeningUnit1: string = 'Screening Unit #1'
   static readonly ScreeningUnitType: string = 'ScreeningUnitType'
   static readonly ScreenThicknessSensor: string = 'ScreenThicknessSensor'
   static readonly SensorType: string = 'SensorType'
   static readonly SerialNumber: string = 'SerialNumber'
   static readonly Shiploader1: string = 'Shiploader #1'
   static readonly ShiploaderType: string = 'ShiploaderType'
   static readonly ShuttleConveyor1: string = 'Shuttle Conveyor #1'
   static readonly ShuttleConveyorType: string = 'ShuttleConveyorType'
   static readonly SpeedSensor: string = 'SpeedSensor'
   static readonly SpeedSensorType: string = 'SpeedSensorType'
   static readonly StartConveyor: string = 'StartConveyor'
   static readonly StateSensorType: string = 'StateSensorType'
   static readonly StockpileColor: string = 'StockpileColor'
   static readonly StockpileCoordinates: string = 'StockpileCoordinates'
   static readonly StockpileHeight: string = 'StockpileHeight'
   static readonly StopConveyor: string = 'StopConveyor'
   static readonly StopLoading: string = 'StopLoading'
   static readonly StorageHall1: string = 'Storage Hall #1'
   static readonly StorageHallType: string = 'StorageHallType'
   static readonly StructuredArrayItemType: string = 'StructuredArrayItemType'
   static readonly TemperatureSensorType: string = 'TemperatureSensorType'
   static readonly TripperCar1: string = 'Tripper Car #1'
   static readonly TripperCarType: string = 'TripperCarType'
   static readonly VibrationSensor: string = 'VibrationSensor'
   static readonly VibrationSensorType: string = 'VibrationSensorType'
   static readonly VoltageSensorType: string = 'VoltageSensorType'
   static readonly VolumeFlowRateSensor: string = 'VolumeFlowRateSensor'
   static readonly VolumeFlowRateSensorType: string = 'VolumeFlowRateSensorType'
   static readonly WearSensorType: string = 'WearSensorType'
}

export class MethodIds {
    static readonly LoadingMachineType_PositioningComplete: string = 'nsu=' + NS + ';i=54'
    static readonly LoadingMachineType_RequestForLoading: string = 'nsu=' + NS + ';i=55'
    static readonly LoadingMachineType_StopLoading: string = 'nsu=' + NS + ';i=56'
    static readonly ConveyorMachineType_StartConveyor: string = 'nsu=' + NS + ';i=218'
    static readonly ConveyorMachineType_StopConveyor: string = 'nsu=' + NS + ';i=219'
    static readonly TripperCar1_PositioningComplete: string = 'nsu=' + NS + ';i=640'
    static readonly TripperCar1_RequestForLoading: string = 'nsu=' + NS + ';i=641'
    static readonly TripperCar1_StopLoading: string = 'nsu=' + NS + ';i=642'
    static readonly Shiploader1_PositioningComplete: string = 'nsu=' + NS + ';i=911'
    static readonly Shiploader1_RequestForLoading: string = 'nsu=' + NS + ';i=912'
    static readonly Shiploader1_StopLoading: string = 'nsu=' + NS + ';i=913'
    static readonly ShuttleConveyor1_StartConveyor: string = 'nsu=' + NS + ';i=991'
    static readonly ShuttleConveyor1_StopConveyor: string = 'nsu=' + NS + ';i=992'
    static readonly Scraper1_PositioningComplete: string = 'nsu=' + NS + ';i=1069'
    static readonly Scraper1_RequestForLoading: string = 'nsu=' + NS + ';i=1070'
    static readonly Scraper1_StopLoading: string = 'nsu=' + NS + ';i=1071'
    static readonly BeltConveyor1_StartConveyor: string = 'nsu=' + NS + ';i=1149'
    static readonly BeltConveyor1_StopConveyor: string = 'nsu=' + NS + ';i=1150'
}

export class ObjectIds {
    static readonly MiningEquipmentType_Identification: string = 'nsu=' + NS + ';i=45'
    static readonly ScraperType_SpeedSensor: string = 'nsu=' + NS + ';i=60'
    static readonly ScraperType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=69'
    static readonly ScraperType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=78'
    static readonly ScraperType_OperatingStateSensor: string = 'nsu=' + NS + ';i=87'
    static readonly ScraperType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=96'
    static readonly ScraperType_PositionSensor: string = 'nsu=' + NS + ';i=105'
    static readonly ScraperType_VibrationSensor: string = 'nsu=' + NS + ';i=115'
    static readonly StorageHallType_HumiditySensor: string = 'nsu=' + NS + ';i=129'
    static readonly StorageHallType_DustConcentrationSensor: string = 'nsu=' + NS + ';i=141'
    static readonly TripperCarType_SpeedSensor: string = 'nsu=' + NS + ';i=151'
    static readonly TripperCarType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=160'
    static readonly TripperCarType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=169'
    static readonly TripperCarType_OperatingStateSensor: string = 'nsu=' + NS + ';i=178'
    static readonly TripperCarType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=187'
    static readonly TripperCarType_PositionSensor: string = 'nsu=' + NS + ';i=196'
    static readonly TripperCarType_VibrationSensor: string = 'nsu=' + NS + ';i=206'
    static readonly BeltConveyorType_BeltSpeedSensor: string = 'nsu=' + NS + ';i=221'
    static readonly BeltConveyorType_VolumeFlowRateSensor: string = 'nsu=' + NS + ';i=230'
    static readonly BeltConveyorType_BeltLoadSensor: string = 'nsu=' + NS + ';i=239'
    static readonly BeltConveyorType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=248'
    static readonly BeltConveyorType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=257'
    static readonly BeltConveyorType_OperatingStateSensor: string = 'nsu=' + NS + ';i=266'
    static readonly BeltConveyorType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=275'
    static readonly BeltConveyorType_VibrationSensor: string = 'nsu=' + NS + ';i=285'
    static readonly BeltConveyorType_BeltAlignmentSensor: string = 'nsu=' + NS + ';i=296'
    static readonly ShuttleConveyorType_LoadingStateSensor: string = 'nsu=' + NS + ';i=306'
    static readonly ShuttleConveyorType_BeltLoadSensor: string = 'nsu=' + NS + ';i=315'
    static readonly ShuttleConveyorType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=324'
    static readonly ShuttleConveyorType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=333'
    static readonly ShuttleConveyorType_OperatingStateSensor: string = 'nsu=' + NS + ';i=342'
    static readonly ShuttleConveyorType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=351'
    static readonly ShuttleConveyorType_VibrationSensor: string = 'nsu=' + NS + ';i=362'
    static readonly ShiploaderType_LoadSensor: string = 'nsu=' + NS + ';i=374'
    static readonly ShiploaderType_SpeedSensor: string = 'nsu=' + NS + ';i=383'
    static readonly ShiploaderType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=392'
    static readonly ShiploaderType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=401'
    static readonly ShiploaderType_OperatingStateSensor: string = 'nsu=' + NS + ';i=410'
    static readonly ShiploaderType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=419'
    static readonly ShiploaderType_VibrationSensor: string = 'nsu=' + NS + ';i=429'
    static readonly AutomaticSamplerType_SamplingArmPositionSensor: string = 'nsu=' + NS + ';i=442'
    static readonly AutomaticSamplerType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=451'
    static readonly AutomaticSamplerType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=460'
    static readonly AutomaticSamplerType_OperatingStateSensor: string = 'nsu=' + NS + ';i=469'
    static readonly AutomaticSamplerType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=478'
    static readonly AutomaticSamplerType_VibrationSensor: string = 'nsu=' + NS + ';i=488'
    static readonly QualityIdentifierType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=501'
    static readonly QualityIdentifierType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=510'
    static readonly QualityIdentifierType_OperatingStateSensor: string = 'nsu=' + NS + ';i=519'
    static readonly QualityIdentifierType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=528'
    static readonly QualityIdentifierType_VibrationSensor: string = 'nsu=' + NS + ';i=538'
    static readonly ScreeningUnitType_MotorCurrentSensor: string = 'nsu=' + NS + ';i=550'
    static readonly ScreeningUnitType_MotorVoltageSensor: string = 'nsu=' + NS + ';i=559'
    static readonly ScreeningUnitType_OperatingStateSensor: string = 'nsu=' + NS + ';i=568'
    static readonly ScreeningUnitType_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=577'
    static readonly ScreeningUnitType_VibrationSensor: string = 'nsu=' + NS + ';i=587'
    static readonly ScreeningUnitType_ScreenThicknessSensor: string = 'nsu=' + NS + ';i=598'
    static readonly StorageHall1: string = 'nsu=' + NS + ';i=607'
    static readonly StorageHall1_HumiditySensor: string = 'nsu=' + NS + ';i=610'
    static readonly StorageHall1_DustConcentrationSensor: string = 'nsu=' + NS + ';i=622'
    static readonly TripperCar1: string = 'nsu=' + NS + ';i=631'
    static readonly TripperCar1_Identification: string = 'nsu=' + NS + ';i=632'
    static readonly TripperCar1_SpeedSensor: string = 'nsu=' + NS + ';i=645'
    static readonly TripperCar1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=654'
    static readonly TripperCar1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=663'
    static readonly TripperCar1_OperatingStateSensor: string = 'nsu=' + NS + ';i=672'
    static readonly TripperCar1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=681'
    static readonly TripperCar1_PositionSensor: string = 'nsu=' + NS + ';i=690'
    static readonly TripperCar1_VibrationSensor: string = 'nsu=' + NS + ';i=700'
    static readonly AutomaticSampler1: string = 'nsu=' + NS + ';i=711'
    static readonly AutomaticSampler1_Identification: string = 'nsu=' + NS + ';i=712'
    static readonly AutomaticSampler1_SamplingArmPositionSensor: string = 'nsu=' + NS + ';i=721'
    static readonly AutomaticSampler1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=730'
    static readonly AutomaticSampler1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=739'
    static readonly AutomaticSampler1_OperatingStateSensor: string = 'nsu=' + NS + ';i=748'
    static readonly AutomaticSampler1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=757'
    static readonly AutomaticSampler1_VibrationSensor: string = 'nsu=' + NS + ';i=767'
    static readonly QualityIdentifier1: string = 'nsu=' + NS + ';i=778'
    static readonly QualityIdentifier1_Identification: string = 'nsu=' + NS + ';i=779'
    static readonly QualityIdentifier1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=788'
    static readonly QualityIdentifier1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=797'
    static readonly QualityIdentifier1_OperatingStateSensor: string = 'nsu=' + NS + ';i=806'
    static readonly QualityIdentifier1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=815'
    static readonly QualityIdentifier1_VibrationSensor: string = 'nsu=' + NS + ';i=825'
    static readonly ScreeningUnit1: string = 'nsu=' + NS + ';i=836'
    static readonly ScreeningUnit1_Identification: string = 'nsu=' + NS + ';i=837'
    static readonly ScreeningUnit1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=845'
    static readonly ScreeningUnit1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=854'
    static readonly ScreeningUnit1_OperatingStateSensor: string = 'nsu=' + NS + ';i=863'
    static readonly ScreeningUnit1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=872'
    static readonly ScreeningUnit1_VibrationSensor: string = 'nsu=' + NS + ';i=882'
    static readonly ScreeningUnit1_ScreenThicknessSensor: string = 'nsu=' + NS + ';i=893'
    static readonly Shiploader1: string = 'nsu=' + NS + ';i=902'
    static readonly Shiploader1_Identification: string = 'nsu=' + NS + ';i=903'
    static readonly Shiploader1_LoadSensor: string = 'nsu=' + NS + ';i=916'
    static readonly Shiploader1_SpeedSensor: string = 'nsu=' + NS + ';i=925'
    static readonly Shiploader1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=934'
    static readonly Shiploader1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=943'
    static readonly Shiploader1_OperatingStateSensor: string = 'nsu=' + NS + ';i=952'
    static readonly Shiploader1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=961'
    static readonly Shiploader1_VibrationSensor: string = 'nsu=' + NS + ';i=971'
    static readonly ShuttleConveyor1: string = 'nsu=' + NS + ';i=982'
    static readonly ShuttleConveyor1_Identification: string = 'nsu=' + NS + ';i=983'
    static readonly ShuttleConveyor1_LoadingStateSensor: string = 'nsu=' + NS + ';i=993'
    static readonly ShuttleConveyor1_BeltLoadSensor: string = 'nsu=' + NS + ';i=1002'
    static readonly ShuttleConveyor1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=1011'
    static readonly ShuttleConveyor1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=1020'
    static readonly ShuttleConveyor1_OperatingStateSensor: string = 'nsu=' + NS + ';i=1029'
    static readonly ShuttleConveyor1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=1038'
    static readonly ShuttleConveyor1_VibrationSensor: string = 'nsu=' + NS + ';i=1049'
    static readonly Scraper1: string = 'nsu=' + NS + ';i=1060'
    static readonly Scraper1_Identification: string = 'nsu=' + NS + ';i=1061'
    static readonly Scraper1_SpeedSensor: string = 'nsu=' + NS + ';i=1074'
    static readonly Scraper1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=1083'
    static readonly Scraper1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=1092'
    static readonly Scraper1_OperatingStateSensor: string = 'nsu=' + NS + ';i=1101'
    static readonly Scraper1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=1110'
    static readonly Scraper1_PositionSensor: string = 'nsu=' + NS + ';i=1119'
    static readonly Scraper1_VibrationSensor: string = 'nsu=' + NS + ';i=1129'
    static readonly BeltConveyor1: string = 'nsu=' + NS + ';i=1140'
    static readonly BeltConveyor1_Identification: string = 'nsu=' + NS + ';i=1141'
    static readonly BeltConveyor1_BeltSpeedSensor: string = 'nsu=' + NS + ';i=1151'
    static readonly BeltConveyor1_VolumeFlowRateSensor: string = 'nsu=' + NS + ';i=1160'
    static readonly BeltConveyor1_BeltLoadSensor: string = 'nsu=' + NS + ';i=1169'
    static readonly BeltConveyor1_MotorCurrentSensor: string = 'nsu=' + NS + ';i=1178'
    static readonly BeltConveyor1_MotorVoltageSensor: string = 'nsu=' + NS + ';i=1187'
    static readonly BeltConveyor1_OperatingStateSensor: string = 'nsu=' + NS + ';i=1196'
    static readonly BeltConveyor1_MotorTemperatureSensor: string = 'nsu=' + NS + ';i=1205'
    static readonly BeltConveyor1_VibrationSensor: string = 'nsu=' + NS + ';i=1215'
    static readonly BeltConveyor1_BeltAlignmentSensor: string = 'nsu=' + NS + ';i=1226'
}

export class ObjectTypeIds {
    static readonly SensorType: string = 'nsu=' + NS + ';i=5'
    static readonly SpeedSensorType: string = 'nsu=' + NS + ';i=14'
    static readonly PositionSensorType: string = 'nsu=' + NS + ';i=15'
    static readonly TemperatureSensorType: string = 'nsu=' + NS + ';i=16'
    static readonly VibrationSensorType: string = 'nsu=' + NS + ';i=17'
    static readonly HumiditySensorType: string = 'nsu=' + NS + ';i=20'
    static readonly DustConcentrationSensorType: string = 'nsu=' + NS + ';i=21'
    static readonly LoadSensorType: string = 'nsu=' + NS + ';i=22'
    static readonly VolumeFlowRateSensorType: string = 'nsu=' + NS + ';i=23'
    static readonly AlignmentSensorType: string = 'nsu=' + NS + ';i=24'
    static readonly LevelSensorType: string = 'nsu=' + NS + ';i=25'
    static readonly CurrentSensorType: string = 'nsu=' + NS + ';i=26'
    static readonly VoltageSensorType: string = 'nsu=' + NS + ';i=27'
    static readonly WearSensorType: string = 'nsu=' + NS + ';i=28'
    static readonly StateSensorType: string = 'nsu=' + NS + ';i=29'
    static readonly MiningEquipmentIdentificationType: string = 'nsu=' + NS + ';i=36'
    static readonly MiningEquipmentType: string = 'nsu=' + NS + ';i=44'
    static readonly LoadingMachineType: string = 'nsu=' + NS + ';i=53'
    static readonly ScraperType: string = 'nsu=' + NS + ';i=59'
    static readonly StorageHallType: string = 'nsu=' + NS + ';i=126'
    static readonly TripperCarType: string = 'nsu=' + NS + ';i=150'
    static readonly ConveyorMachineType: string = 'nsu=' + NS + ';i=217'
    static readonly BeltConveyorType: string = 'nsu=' + NS + ';i=220'
    static readonly ShuttleConveyorType: string = 'nsu=' + NS + ';i=305'
    static readonly ShiploaderType: string = 'nsu=' + NS + ';i=373'
    static readonly AutomaticSamplerType: string = 'nsu=' + NS + ';i=440'
    static readonly QualityIdentifierType: string = 'nsu=' + NS + ';i=499'
    static readonly ScreeningUnitType: string = 'nsu=' + NS + ';i=549'
}

export class VariableIds {
    static readonly StructuredArrayItemType_EngineeringUnits: string = 'nsu=' + NS + ';i=2'
    static readonly StructuredArrayItemType_EURange: string = 'nsu=' + NS + ';i=3'
    static readonly StructuredArrayItemType_InstrumentRange: string = 'nsu=' + NS + ';i=4'
    static readonly SensorType_Measurement: string = 'nsu=' + NS + ';i=6'
    static readonly SensorType_Measurement_EURange: string = 'nsu=' + NS + ';i=10'
    static readonly SensorType_EngineeringUnits: string = 'nsu=' + NS + ';i=12'
    static readonly SensorType_EURange: string = 'nsu=' + NS + ';i=13'
    static readonly VibrationSensorType_Frequency: string = 'nsu=' + NS + ';i=18'
    static readonly VibrationSensorType_Amplitude: string = 'nsu=' + NS + ';i=19'
    static readonly StateSensorType_Measurement: string = 'nsu=' + NS + ';i=30'
    static readonly StateSensorType_Measurement_EURange: string = 'nsu=' + NS + ';i=34'
    static readonly MiningEquipmentIdentificationType_AssetId: string = 'nsu=' + NS + ';i=37'
    static readonly MiningEquipmentIdentificationType_DeviceClass: string = 'nsu=' + NS + ';i=38'
    static readonly MiningEquipmentIdentificationType_Manufacturer: string = 'nsu=' + NS + ';i=39'
    static readonly MiningEquipmentIdentificationType_ManufacturerUri: string = 'nsu=' + NS + ';i=40'
    static readonly MiningEquipmentIdentificationType_Model: string = 'nsu=' + NS + ';i=41'
    static readonly MiningEquipmentIdentificationType_ProductInstanceUri: string = 'nsu=' + NS + ';i=42'
    static readonly MiningEquipmentIdentificationType_SerialNumber: string = 'nsu=' + NS + ';i=43'
    static readonly MiningEquipmentType_Identification_AssetId: string = 'nsu=' + NS + ';i=46'
    static readonly MiningEquipmentType_Identification_DeviceClass: string = 'nsu=' + NS + ';i=47'
    static readonly MiningEquipmentType_Identification_Manufacturer: string = 'nsu=' + NS + ';i=48'
    static readonly MiningEquipmentType_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=49'
    static readonly MiningEquipmentType_Identification_Model: string = 'nsu=' + NS + ';i=50'
    static readonly MiningEquipmentType_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=51'
    static readonly MiningEquipmentType_Identification_SerialNumber: string = 'nsu=' + NS + ';i=52'
    static readonly LoadingMachineType_ExclusionZone: string = 'nsu=' + NS + ';i=57'
    static readonly LoadingMachineType_MachinePose: string = 'nsu=' + NS + ';i=58'
    static readonly ScraperType_SpeedSensor_Measurement: string = 'nsu=' + NS + ';i=61'
    static readonly ScraperType_SpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=65'
    static readonly ScraperType_SpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=67'
    static readonly ScraperType_SpeedSensor_EURange: string = 'nsu=' + NS + ';i=68'
    static readonly ScraperType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=70'
    static readonly ScraperType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=74'
    static readonly ScraperType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=76'
    static readonly ScraperType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=77'
    static readonly ScraperType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=79'
    static readonly ScraperType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=83'
    static readonly ScraperType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=85'
    static readonly ScraperType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=86'
    static readonly ScraperType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=88'
    static readonly ScraperType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=92'
    static readonly ScraperType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=94'
    static readonly ScraperType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=95'
    static readonly ScraperType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=97'
    static readonly ScraperType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=101'
    static readonly ScraperType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=103'
    static readonly ScraperType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=104'
    static readonly ScraperType_PositionSensor_Measurement: string = 'nsu=' + NS + ';i=106'
    static readonly ScraperType_PositionSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=110'
    static readonly ScraperType_PositionSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=112'
    static readonly ScraperType_PositionSensor_EURange: string = 'nsu=' + NS + ';i=113'
    static readonly ScraperType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=114'
    static readonly ScraperType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=116'
    static readonly ScraperType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=120'
    static readonly ScraperType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=122'
    static readonly ScraperType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=123'
    static readonly ScraperType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=124'
    static readonly ScraperType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=125'
    static readonly StorageHallType_StockpileCoordinates: string = 'nsu=' + NS + ';i=127'
    static readonly StorageHallType_DistanceBetweenStockpiles: string = 'nsu=' + NS + ';i=128'
    static readonly StorageHallType_HumiditySensor_Measurement: string = 'nsu=' + NS + ';i=130'
    static readonly StorageHallType_HumiditySensor_Measurement_EURange: string = 'nsu=' + NS + ';i=134'
    static readonly StorageHallType_HumiditySensor_EngineeringUnits: string = 'nsu=' + NS + ';i=136'
    static readonly StorageHallType_HumiditySensor_EURange: string = 'nsu=' + NS + ';i=137'
    static readonly StorageHallType_FillingRate: string = 'nsu=' + NS + ';i=138'
    static readonly StorageHallType_StockpileHeight: string = 'nsu=' + NS + ';i=139'
    static readonly StorageHallType_StockpileColor: string = 'nsu=' + NS + ';i=140'
    static readonly StorageHallType_DustConcentrationSensor_Measurement: string = 'nsu=' + NS + ';i=142'
    static readonly StorageHallType_DustConcentrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=146'
    static readonly StorageHallType_DustConcentrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=148'
    static readonly StorageHallType_DustConcentrationSensor_EURange: string = 'nsu=' + NS + ';i=149'
    static readonly TripperCarType_SpeedSensor_Measurement: string = 'nsu=' + NS + ';i=152'
    static readonly TripperCarType_SpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=156'
    static readonly TripperCarType_SpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=158'
    static readonly TripperCarType_SpeedSensor_EURange: string = 'nsu=' + NS + ';i=159'
    static readonly TripperCarType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=161'
    static readonly TripperCarType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=165'
    static readonly TripperCarType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=167'
    static readonly TripperCarType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=168'
    static readonly TripperCarType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=170'
    static readonly TripperCarType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=174'
    static readonly TripperCarType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=176'
    static readonly TripperCarType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=177'
    static readonly TripperCarType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=179'
    static readonly TripperCarType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=183'
    static readonly TripperCarType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=185'
    static readonly TripperCarType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=186'
    static readonly TripperCarType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=188'
    static readonly TripperCarType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=192'
    static readonly TripperCarType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=194'
    static readonly TripperCarType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=195'
    static readonly TripperCarType_PositionSensor_Measurement: string = 'nsu=' + NS + ';i=197'
    static readonly TripperCarType_PositionSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=201'
    static readonly TripperCarType_PositionSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=203'
    static readonly TripperCarType_PositionSensor_EURange: string = 'nsu=' + NS + ';i=204'
    static readonly TripperCarType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=205'
    static readonly TripperCarType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=207'
    static readonly TripperCarType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=211'
    static readonly TripperCarType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=213'
    static readonly TripperCarType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=214'
    static readonly TripperCarType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=215'
    static readonly TripperCarType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=216'
    static readonly BeltConveyorType_BeltSpeedSensor_Measurement: string = 'nsu=' + NS + ';i=222'
    static readonly BeltConveyorType_BeltSpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=226'
    static readonly BeltConveyorType_BeltSpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=228'
    static readonly BeltConveyorType_BeltSpeedSensor_EURange: string = 'nsu=' + NS + ';i=229'
    static readonly BeltConveyorType_VolumeFlowRateSensor_Measurement: string = 'nsu=' + NS + ';i=231'
    static readonly BeltConveyorType_VolumeFlowRateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=235'
    static readonly BeltConveyorType_VolumeFlowRateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=237'
    static readonly BeltConveyorType_VolumeFlowRateSensor_EURange: string = 'nsu=' + NS + ';i=238'
    static readonly BeltConveyorType_BeltLoadSensor_Measurement: string = 'nsu=' + NS + ';i=240'
    static readonly BeltConveyorType_BeltLoadSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=244'
    static readonly BeltConveyorType_BeltLoadSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=246'
    static readonly BeltConveyorType_BeltLoadSensor_EURange: string = 'nsu=' + NS + ';i=247'
    static readonly BeltConveyorType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=249'
    static readonly BeltConveyorType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=253'
    static readonly BeltConveyorType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=255'
    static readonly BeltConveyorType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=256'
    static readonly BeltConveyorType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=258'
    static readonly BeltConveyorType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=262'
    static readonly BeltConveyorType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=264'
    static readonly BeltConveyorType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=265'
    static readonly BeltConveyorType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=267'
    static readonly BeltConveyorType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=271'
    static readonly BeltConveyorType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=273'
    static readonly BeltConveyorType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=274'
    static readonly BeltConveyorType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=276'
    static readonly BeltConveyorType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=280'
    static readonly BeltConveyorType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=282'
    static readonly BeltConveyorType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=283'
    static readonly BeltConveyorType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=284'
    static readonly BeltConveyorType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=286'
    static readonly BeltConveyorType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=290'
    static readonly BeltConveyorType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=292'
    static readonly BeltConveyorType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=293'
    static readonly BeltConveyorType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=294'
    static readonly BeltConveyorType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=295'
    static readonly BeltConveyorType_BeltAlignmentSensor_Measurement: string = 'nsu=' + NS + ';i=297'
    static readonly BeltConveyorType_BeltAlignmentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=301'
    static readonly BeltConveyorType_BeltAlignmentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=303'
    static readonly BeltConveyorType_BeltAlignmentSensor_EURange: string = 'nsu=' + NS + ';i=304'
    static readonly ShuttleConveyorType_LoadingStateSensor_Measurement: string = 'nsu=' + NS + ';i=307'
    static readonly ShuttleConveyorType_LoadingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=311'
    static readonly ShuttleConveyorType_LoadingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=313'
    static readonly ShuttleConveyorType_LoadingStateSensor_EURange: string = 'nsu=' + NS + ';i=314'
    static readonly ShuttleConveyorType_BeltLoadSensor_Measurement: string = 'nsu=' + NS + ';i=316'
    static readonly ShuttleConveyorType_BeltLoadSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=320'
    static readonly ShuttleConveyorType_BeltLoadSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=322'
    static readonly ShuttleConveyorType_BeltLoadSensor_EURange: string = 'nsu=' + NS + ';i=323'
    static readonly ShuttleConveyorType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=325'
    static readonly ShuttleConveyorType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=329'
    static readonly ShuttleConveyorType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=331'
    static readonly ShuttleConveyorType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=332'
    static readonly ShuttleConveyorType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=334'
    static readonly ShuttleConveyorType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=338'
    static readonly ShuttleConveyorType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=340'
    static readonly ShuttleConveyorType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=341'
    static readonly ShuttleConveyorType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=343'
    static readonly ShuttleConveyorType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=347'
    static readonly ShuttleConveyorType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=349'
    static readonly ShuttleConveyorType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=350'
    static readonly ShuttleConveyorType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=352'
    static readonly ShuttleConveyorType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=356'
    static readonly ShuttleConveyorType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=358'
    static readonly ShuttleConveyorType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=359'
    static readonly ShuttleConveyorType_DirectionSignal: string = 'nsu=' + NS + ';i=360'
    static readonly ShuttleConveyorType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=361'
    static readonly ShuttleConveyorType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=363'
    static readonly ShuttleConveyorType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=367'
    static readonly ShuttleConveyorType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=369'
    static readonly ShuttleConveyorType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=370'
    static readonly ShuttleConveyorType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=371'
    static readonly ShuttleConveyorType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=372'
    static readonly ShiploaderType_LoadSensor_Measurement: string = 'nsu=' + NS + ';i=375'
    static readonly ShiploaderType_LoadSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=379'
    static readonly ShiploaderType_LoadSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=381'
    static readonly ShiploaderType_LoadSensor_EURange: string = 'nsu=' + NS + ';i=382'
    static readonly ShiploaderType_SpeedSensor_Measurement: string = 'nsu=' + NS + ';i=384'
    static readonly ShiploaderType_SpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=388'
    static readonly ShiploaderType_SpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=390'
    static readonly ShiploaderType_SpeedSensor_EURange: string = 'nsu=' + NS + ';i=391'
    static readonly ShiploaderType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=393'
    static readonly ShiploaderType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=397'
    static readonly ShiploaderType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=399'
    static readonly ShiploaderType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=400'
    static readonly ShiploaderType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=402'
    static readonly ShiploaderType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=406'
    static readonly ShiploaderType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=408'
    static readonly ShiploaderType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=409'
    static readonly ShiploaderType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=411'
    static readonly ShiploaderType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=415'
    static readonly ShiploaderType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=417'
    static readonly ShiploaderType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=418'
    static readonly ShiploaderType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=420'
    static readonly ShiploaderType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=424'
    static readonly ShiploaderType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=426'
    static readonly ShiploaderType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=427'
    static readonly ShiploaderType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=428'
    static readonly ShiploaderType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=430'
    static readonly ShiploaderType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=434'
    static readonly ShiploaderType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=436'
    static readonly ShiploaderType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=437'
    static readonly ShiploaderType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=438'
    static readonly ShiploaderType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=439'
    static readonly AutomaticSamplerType_SamplingFrequency: string = 'nsu=' + NS + ';i=441'
    static readonly AutomaticSamplerType_SamplingArmPositionSensor_Measurement: string = 'nsu=' + NS + ';i=443'
    static readonly AutomaticSamplerType_SamplingArmPositionSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=447'
    static readonly AutomaticSamplerType_SamplingArmPositionSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=449'
    static readonly AutomaticSamplerType_SamplingArmPositionSensor_EURange: string = 'nsu=' + NS + ';i=450'
    static readonly AutomaticSamplerType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=452'
    static readonly AutomaticSamplerType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=456'
    static readonly AutomaticSamplerType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=458'
    static readonly AutomaticSamplerType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=459'
    static readonly AutomaticSamplerType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=461'
    static readonly AutomaticSamplerType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=465'
    static readonly AutomaticSamplerType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=467'
    static readonly AutomaticSamplerType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=468'
    static readonly AutomaticSamplerType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=470'
    static readonly AutomaticSamplerType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=474'
    static readonly AutomaticSamplerType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=476'
    static readonly AutomaticSamplerType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=477'
    static readonly AutomaticSamplerType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=479'
    static readonly AutomaticSamplerType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=483'
    static readonly AutomaticSamplerType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=485'
    static readonly AutomaticSamplerType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=486'
    static readonly AutomaticSamplerType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=487'
    static readonly AutomaticSamplerType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=489'
    static readonly AutomaticSamplerType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=493'
    static readonly AutomaticSamplerType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=495'
    static readonly AutomaticSamplerType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=496'
    static readonly AutomaticSamplerType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=497'
    static readonly AutomaticSamplerType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=498'
    static readonly QualityIdentifierType_EmissionSpectrum: string = 'nsu=' + NS + ';i=500'
    static readonly QualityIdentifierType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=502'
    static readonly QualityIdentifierType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=506'
    static readonly QualityIdentifierType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=508'
    static readonly QualityIdentifierType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=509'
    static readonly QualityIdentifierType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=511'
    static readonly QualityIdentifierType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=515'
    static readonly QualityIdentifierType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=517'
    static readonly QualityIdentifierType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=518'
    static readonly QualityIdentifierType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=520'
    static readonly QualityIdentifierType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=524'
    static readonly QualityIdentifierType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=526'
    static readonly QualityIdentifierType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=527'
    static readonly QualityIdentifierType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=529'
    static readonly QualityIdentifierType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=533'
    static readonly QualityIdentifierType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=535'
    static readonly QualityIdentifierType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=536'
    static readonly QualityIdentifierType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=537'
    static readonly QualityIdentifierType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=539'
    static readonly QualityIdentifierType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=543'
    static readonly QualityIdentifierType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=545'
    static readonly QualityIdentifierType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=546'
    static readonly QualityIdentifierType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=547'
    static readonly QualityIdentifierType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=548'
    static readonly ScreeningUnitType_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=551'
    static readonly ScreeningUnitType_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=555'
    static readonly ScreeningUnitType_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=557'
    static readonly ScreeningUnitType_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=558'
    static readonly ScreeningUnitType_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=560'
    static readonly ScreeningUnitType_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=564'
    static readonly ScreeningUnitType_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=566'
    static readonly ScreeningUnitType_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=567'
    static readonly ScreeningUnitType_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=569'
    static readonly ScreeningUnitType_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=573'
    static readonly ScreeningUnitType_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=575'
    static readonly ScreeningUnitType_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=576'
    static readonly ScreeningUnitType_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=578'
    static readonly ScreeningUnitType_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=582'
    static readonly ScreeningUnitType_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=584'
    static readonly ScreeningUnitType_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=585'
    static readonly ScreeningUnitType_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=586'
    static readonly ScreeningUnitType_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=588'
    static readonly ScreeningUnitType_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=592'
    static readonly ScreeningUnitType_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=594'
    static readonly ScreeningUnitType_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=595'
    static readonly ScreeningUnitType_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=596'
    static readonly ScreeningUnitType_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=597'
    static readonly ScreeningUnitType_ScreenThicknessSensor_Measurement: string = 'nsu=' + NS + ';i=599'
    static readonly ScreeningUnitType_ScreenThicknessSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=603'
    static readonly ScreeningUnitType_ScreenThicknessSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=605'
    static readonly ScreeningUnitType_ScreenThicknessSensor_EURange: string = 'nsu=' + NS + ';i=606'
    static readonly StorageHall1_StockpileCoordinates: string = 'nsu=' + NS + ';i=608'
    static readonly StorageHall1_DistanceBetweenStockpiles: string = 'nsu=' + NS + ';i=609'
    static readonly StorageHall1_HumiditySensor_Measurement: string = 'nsu=' + NS + ';i=611'
    static readonly StorageHall1_HumiditySensor_Measurement_EURange: string = 'nsu=' + NS + ';i=615'
    static readonly StorageHall1_HumiditySensor_EngineeringUnits: string = 'nsu=' + NS + ';i=617'
    static readonly StorageHall1_HumiditySensor_EURange: string = 'nsu=' + NS + ';i=618'
    static readonly StorageHall1_FillingRate: string = 'nsu=' + NS + ';i=619'
    static readonly StorageHall1_StockpileHeight: string = 'nsu=' + NS + ';i=620'
    static readonly StorageHall1_StockpileColor: string = 'nsu=' + NS + ';i=621'
    static readonly StorageHall1_DustConcentrationSensor_Measurement: string = 'nsu=' + NS + ';i=623'
    static readonly StorageHall1_DustConcentrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=627'
    static readonly StorageHall1_DustConcentrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=629'
    static readonly StorageHall1_DustConcentrationSensor_EURange: string = 'nsu=' + NS + ';i=630'
    static readonly TripperCar1_Identification_AssetId: string = 'nsu=' + NS + ';i=633'
    static readonly TripperCar1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=634'
    static readonly TripperCar1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=635'
    static readonly TripperCar1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=636'
    static readonly TripperCar1_Identification_Model: string = 'nsu=' + NS + ';i=637'
    static readonly TripperCar1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=638'
    static readonly TripperCar1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=639'
    static readonly TripperCar1_ExclusionZone: string = 'nsu=' + NS + ';i=643'
    static readonly TripperCar1_MachinePose: string = 'nsu=' + NS + ';i=644'
    static readonly TripperCar1_SpeedSensor_Measurement: string = 'nsu=' + NS + ';i=646'
    static readonly TripperCar1_SpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=650'
    static readonly TripperCar1_SpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=652'
    static readonly TripperCar1_SpeedSensor_EURange: string = 'nsu=' + NS + ';i=653'
    static readonly TripperCar1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=655'
    static readonly TripperCar1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=659'
    static readonly TripperCar1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=661'
    static readonly TripperCar1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=662'
    static readonly TripperCar1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=664'
    static readonly TripperCar1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=668'
    static readonly TripperCar1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=670'
    static readonly TripperCar1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=671'
    static readonly TripperCar1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=673'
    static readonly TripperCar1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=677'
    static readonly TripperCar1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=679'
    static readonly TripperCar1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=680'
    static readonly TripperCar1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=682'
    static readonly TripperCar1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=686'
    static readonly TripperCar1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=688'
    static readonly TripperCar1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=689'
    static readonly TripperCar1_PositionSensor_Measurement: string = 'nsu=' + NS + ';i=691'
    static readonly TripperCar1_PositionSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=695'
    static readonly TripperCar1_PositionSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=697'
    static readonly TripperCar1_PositionSensor_EURange: string = 'nsu=' + NS + ';i=698'
    static readonly TripperCar1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=699'
    static readonly TripperCar1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=701'
    static readonly TripperCar1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=705'
    static readonly TripperCar1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=707'
    static readonly TripperCar1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=708'
    static readonly TripperCar1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=709'
    static readonly TripperCar1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=710'
    static readonly AutomaticSampler1_Identification_AssetId: string = 'nsu=' + NS + ';i=713'
    static readonly AutomaticSampler1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=714'
    static readonly AutomaticSampler1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=715'
    static readonly AutomaticSampler1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=716'
    static readonly AutomaticSampler1_Identification_Model: string = 'nsu=' + NS + ';i=717'
    static readonly AutomaticSampler1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=718'
    static readonly AutomaticSampler1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=719'
    static readonly AutomaticSampler1_SamplingFrequency: string = 'nsu=' + NS + ';i=720'
    static readonly AutomaticSampler1_SamplingArmPositionSensor_Measurement: string = 'nsu=' + NS + ';i=722'
    static readonly AutomaticSampler1_SamplingArmPositionSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=726'
    static readonly AutomaticSampler1_SamplingArmPositionSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=728'
    static readonly AutomaticSampler1_SamplingArmPositionSensor_EURange: string = 'nsu=' + NS + ';i=729'
    static readonly AutomaticSampler1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=731'
    static readonly AutomaticSampler1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=735'
    static readonly AutomaticSampler1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=737'
    static readonly AutomaticSampler1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=738'
    static readonly AutomaticSampler1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=740'
    static readonly AutomaticSampler1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=744'
    static readonly AutomaticSampler1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=746'
    static readonly AutomaticSampler1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=747'
    static readonly AutomaticSampler1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=749'
    static readonly AutomaticSampler1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=753'
    static readonly AutomaticSampler1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=755'
    static readonly AutomaticSampler1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=756'
    static readonly AutomaticSampler1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=758'
    static readonly AutomaticSampler1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=762'
    static readonly AutomaticSampler1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=764'
    static readonly AutomaticSampler1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=765'
    static readonly AutomaticSampler1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=766'
    static readonly AutomaticSampler1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=768'
    static readonly AutomaticSampler1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=772'
    static readonly AutomaticSampler1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=774'
    static readonly AutomaticSampler1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=775'
    static readonly AutomaticSampler1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=776'
    static readonly AutomaticSampler1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=777'
    static readonly QualityIdentifier1_Identification_AssetId: string = 'nsu=' + NS + ';i=780'
    static readonly QualityIdentifier1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=781'
    static readonly QualityIdentifier1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=782'
    static readonly QualityIdentifier1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=783'
    static readonly QualityIdentifier1_Identification_Model: string = 'nsu=' + NS + ';i=784'
    static readonly QualityIdentifier1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=785'
    static readonly QualityIdentifier1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=786'
    static readonly QualityIdentifier1_EmissionSpectrum: string = 'nsu=' + NS + ';i=787'
    static readonly QualityIdentifier1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=789'
    static readonly QualityIdentifier1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=793'
    static readonly QualityIdentifier1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=795'
    static readonly QualityIdentifier1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=796'
    static readonly QualityIdentifier1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=798'
    static readonly QualityIdentifier1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=802'
    static readonly QualityIdentifier1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=804'
    static readonly QualityIdentifier1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=805'
    static readonly QualityIdentifier1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=807'
    static readonly QualityIdentifier1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=811'
    static readonly QualityIdentifier1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=813'
    static readonly QualityIdentifier1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=814'
    static readonly QualityIdentifier1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=816'
    static readonly QualityIdentifier1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=820'
    static readonly QualityIdentifier1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=822'
    static readonly QualityIdentifier1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=823'
    static readonly QualityIdentifier1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=824'
    static readonly QualityIdentifier1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=826'
    static readonly QualityIdentifier1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=830'
    static readonly QualityIdentifier1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=832'
    static readonly QualityIdentifier1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=833'
    static readonly QualityIdentifier1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=834'
    static readonly QualityIdentifier1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=835'
    static readonly ScreeningUnit1_Identification_AssetId: string = 'nsu=' + NS + ';i=838'
    static readonly ScreeningUnit1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=839'
    static readonly ScreeningUnit1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=840'
    static readonly ScreeningUnit1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=841'
    static readonly ScreeningUnit1_Identification_Model: string = 'nsu=' + NS + ';i=842'
    static readonly ScreeningUnit1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=843'
    static readonly ScreeningUnit1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=844'
    static readonly ScreeningUnit1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=846'
    static readonly ScreeningUnit1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=850'
    static readonly ScreeningUnit1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=852'
    static readonly ScreeningUnit1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=853'
    static readonly ScreeningUnit1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=855'
    static readonly ScreeningUnit1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=859'
    static readonly ScreeningUnit1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=861'
    static readonly ScreeningUnit1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=862'
    static readonly ScreeningUnit1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=864'
    static readonly ScreeningUnit1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=868'
    static readonly ScreeningUnit1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=870'
    static readonly ScreeningUnit1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=871'
    static readonly ScreeningUnit1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=873'
    static readonly ScreeningUnit1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=877'
    static readonly ScreeningUnit1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=879'
    static readonly ScreeningUnit1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=880'
    static readonly ScreeningUnit1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=881'
    static readonly ScreeningUnit1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=883'
    static readonly ScreeningUnit1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=887'
    static readonly ScreeningUnit1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=889'
    static readonly ScreeningUnit1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=890'
    static readonly ScreeningUnit1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=891'
    static readonly ScreeningUnit1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=892'
    static readonly ScreeningUnit1_ScreenThicknessSensor_Measurement: string = 'nsu=' + NS + ';i=894'
    static readonly ScreeningUnit1_ScreenThicknessSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=898'
    static readonly ScreeningUnit1_ScreenThicknessSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=900'
    static readonly ScreeningUnit1_ScreenThicknessSensor_EURange: string = 'nsu=' + NS + ';i=901'
    static readonly Shiploader1_Identification_AssetId: string = 'nsu=' + NS + ';i=904'
    static readonly Shiploader1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=905'
    static readonly Shiploader1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=906'
    static readonly Shiploader1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=907'
    static readonly Shiploader1_Identification_Model: string = 'nsu=' + NS + ';i=908'
    static readonly Shiploader1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=909'
    static readonly Shiploader1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=910'
    static readonly Shiploader1_ExclusionZone: string = 'nsu=' + NS + ';i=914'
    static readonly Shiploader1_MachinePose: string = 'nsu=' + NS + ';i=915'
    static readonly Shiploader1_LoadSensor_Measurement: string = 'nsu=' + NS + ';i=917'
    static readonly Shiploader1_LoadSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=921'
    static readonly Shiploader1_LoadSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=923'
    static readonly Shiploader1_LoadSensor_EURange: string = 'nsu=' + NS + ';i=924'
    static readonly Shiploader1_SpeedSensor_Measurement: string = 'nsu=' + NS + ';i=926'
    static readonly Shiploader1_SpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=930'
    static readonly Shiploader1_SpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=932'
    static readonly Shiploader1_SpeedSensor_EURange: string = 'nsu=' + NS + ';i=933'
    static readonly Shiploader1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=935'
    static readonly Shiploader1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=939'
    static readonly Shiploader1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=941'
    static readonly Shiploader1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=942'
    static readonly Shiploader1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=944'
    static readonly Shiploader1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=948'
    static readonly Shiploader1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=950'
    static readonly Shiploader1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=951'
    static readonly Shiploader1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=953'
    static readonly Shiploader1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=957'
    static readonly Shiploader1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=959'
    static readonly Shiploader1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=960'
    static readonly Shiploader1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=962'
    static readonly Shiploader1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=966'
    static readonly Shiploader1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=968'
    static readonly Shiploader1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=969'
    static readonly Shiploader1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=970'
    static readonly Shiploader1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=972'
    static readonly Shiploader1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=976'
    static readonly Shiploader1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=978'
    static readonly Shiploader1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=979'
    static readonly Shiploader1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=980'
    static readonly Shiploader1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=981'
    static readonly ShuttleConveyor1_Identification_AssetId: string = 'nsu=' + NS + ';i=984'
    static readonly ShuttleConveyor1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=985'
    static readonly ShuttleConveyor1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=986'
    static readonly ShuttleConveyor1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=987'
    static readonly ShuttleConveyor1_Identification_Model: string = 'nsu=' + NS + ';i=988'
    static readonly ShuttleConveyor1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=989'
    static readonly ShuttleConveyor1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=990'
    static readonly ShuttleConveyor1_LoadingStateSensor_Measurement: string = 'nsu=' + NS + ';i=994'
    static readonly ShuttleConveyor1_LoadingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=998'
    static readonly ShuttleConveyor1_LoadingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1000'
    static readonly ShuttleConveyor1_LoadingStateSensor_EURange: string = 'nsu=' + NS + ';i=1001'
    static readonly ShuttleConveyor1_BeltLoadSensor_Measurement: string = 'nsu=' + NS + ';i=1003'
    static readonly ShuttleConveyor1_BeltLoadSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1007'
    static readonly ShuttleConveyor1_BeltLoadSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1009'
    static readonly ShuttleConveyor1_BeltLoadSensor_EURange: string = 'nsu=' + NS + ';i=1010'
    static readonly ShuttleConveyor1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=1012'
    static readonly ShuttleConveyor1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1016'
    static readonly ShuttleConveyor1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1018'
    static readonly ShuttleConveyor1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=1019'
    static readonly ShuttleConveyor1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=1021'
    static readonly ShuttleConveyor1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1025'
    static readonly ShuttleConveyor1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1027'
    static readonly ShuttleConveyor1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=1028'
    static readonly ShuttleConveyor1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=1030'
    static readonly ShuttleConveyor1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1034'
    static readonly ShuttleConveyor1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1036'
    static readonly ShuttleConveyor1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=1037'
    static readonly ShuttleConveyor1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=1039'
    static readonly ShuttleConveyor1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1043'
    static readonly ShuttleConveyor1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1045'
    static readonly ShuttleConveyor1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=1046'
    static readonly ShuttleConveyor1_DirectionSignal: string = 'nsu=' + NS + ';i=1047'
    static readonly ShuttleConveyor1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=1048'
    static readonly ShuttleConveyor1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=1050'
    static readonly ShuttleConveyor1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1054'
    static readonly ShuttleConveyor1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1056'
    static readonly ShuttleConveyor1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=1057'
    static readonly ShuttleConveyor1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=1058'
    static readonly ShuttleConveyor1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=1059'
    static readonly Scraper1_Identification_AssetId: string = 'nsu=' + NS + ';i=1062'
    static readonly Scraper1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=1063'
    static readonly Scraper1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=1064'
    static readonly Scraper1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=1065'
    static readonly Scraper1_Identification_Model: string = 'nsu=' + NS + ';i=1066'
    static readonly Scraper1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=1067'
    static readonly Scraper1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=1068'
    static readonly Scraper1_ExclusionZone: string = 'nsu=' + NS + ';i=1072'
    static readonly Scraper1_MachinePose: string = 'nsu=' + NS + ';i=1073'
    static readonly Scraper1_SpeedSensor_Measurement: string = 'nsu=' + NS + ';i=1075'
    static readonly Scraper1_SpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1079'
    static readonly Scraper1_SpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1081'
    static readonly Scraper1_SpeedSensor_EURange: string = 'nsu=' + NS + ';i=1082'
    static readonly Scraper1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=1084'
    static readonly Scraper1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1088'
    static readonly Scraper1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1090'
    static readonly Scraper1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=1091'
    static readonly Scraper1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=1093'
    static readonly Scraper1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1097'
    static readonly Scraper1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1099'
    static readonly Scraper1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=1100'
    static readonly Scraper1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=1102'
    static readonly Scraper1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1106'
    static readonly Scraper1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1108'
    static readonly Scraper1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=1109'
    static readonly Scraper1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=1111'
    static readonly Scraper1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1115'
    static readonly Scraper1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1117'
    static readonly Scraper1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=1118'
    static readonly Scraper1_PositionSensor_Measurement: string = 'nsu=' + NS + ';i=1120'
    static readonly Scraper1_PositionSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1124'
    static readonly Scraper1_PositionSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1126'
    static readonly Scraper1_PositionSensor_EURange: string = 'nsu=' + NS + ';i=1127'
    static readonly Scraper1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=1128'
    static readonly Scraper1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=1130'
    static readonly Scraper1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1134'
    static readonly Scraper1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1136'
    static readonly Scraper1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=1137'
    static readonly Scraper1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=1138'
    static readonly Scraper1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=1139'
    static readonly BeltConveyor1_Identification_AssetId: string = 'nsu=' + NS + ';i=1142'
    static readonly BeltConveyor1_Identification_DeviceClass: string = 'nsu=' + NS + ';i=1143'
    static readonly BeltConveyor1_Identification_Manufacturer: string = 'nsu=' + NS + ';i=1144'
    static readonly BeltConveyor1_Identification_ManufacturerUri: string = 'nsu=' + NS + ';i=1145'
    static readonly BeltConveyor1_Identification_Model: string = 'nsu=' + NS + ';i=1146'
    static readonly BeltConveyor1_Identification_ProductInstanceUri: string = 'nsu=' + NS + ';i=1147'
    static readonly BeltConveyor1_Identification_SerialNumber: string = 'nsu=' + NS + ';i=1148'
    static readonly BeltConveyor1_BeltSpeedSensor_Measurement: string = 'nsu=' + NS + ';i=1152'
    static readonly BeltConveyor1_BeltSpeedSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1156'
    static readonly BeltConveyor1_BeltSpeedSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1158'
    static readonly BeltConveyor1_BeltSpeedSensor_EURange: string = 'nsu=' + NS + ';i=1159'
    static readonly BeltConveyor1_VolumeFlowRateSensor_Measurement: string = 'nsu=' + NS + ';i=1161'
    static readonly BeltConveyor1_VolumeFlowRateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1165'
    static readonly BeltConveyor1_VolumeFlowRateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1167'
    static readonly BeltConveyor1_VolumeFlowRateSensor_EURange: string = 'nsu=' + NS + ';i=1168'
    static readonly BeltConveyor1_BeltLoadSensor_Measurement: string = 'nsu=' + NS + ';i=1170'
    static readonly BeltConveyor1_BeltLoadSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1174'
    static readonly BeltConveyor1_BeltLoadSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1176'
    static readonly BeltConveyor1_BeltLoadSensor_EURange: string = 'nsu=' + NS + ';i=1177'
    static readonly BeltConveyor1_MotorCurrentSensor_Measurement: string = 'nsu=' + NS + ';i=1179'
    static readonly BeltConveyor1_MotorCurrentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1183'
    static readonly BeltConveyor1_MotorCurrentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1185'
    static readonly BeltConveyor1_MotorCurrentSensor_EURange: string = 'nsu=' + NS + ';i=1186'
    static readonly BeltConveyor1_MotorVoltageSensor_Measurement: string = 'nsu=' + NS + ';i=1188'
    static readonly BeltConveyor1_MotorVoltageSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1192'
    static readonly BeltConveyor1_MotorVoltageSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1194'
    static readonly BeltConveyor1_MotorVoltageSensor_EURange: string = 'nsu=' + NS + ';i=1195'
    static readonly BeltConveyor1_OperatingStateSensor_Measurement: string = 'nsu=' + NS + ';i=1197'
    static readonly BeltConveyor1_OperatingStateSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1201'
    static readonly BeltConveyor1_OperatingStateSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1203'
    static readonly BeltConveyor1_OperatingStateSensor_EURange: string = 'nsu=' + NS + ';i=1204'
    static readonly BeltConveyor1_MotorTemperatureSensor_Measurement: string = 'nsu=' + NS + ';i=1206'
    static readonly BeltConveyor1_MotorTemperatureSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1210'
    static readonly BeltConveyor1_MotorTemperatureSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1212'
    static readonly BeltConveyor1_MotorTemperatureSensor_EURange: string = 'nsu=' + NS + ';i=1213'
    static readonly BeltConveyor1_CumulativeEnergyUsed: string = 'nsu=' + NS + ';i=1214'
    static readonly BeltConveyor1_VibrationSensor_Measurement: string = 'nsu=' + NS + ';i=1216'
    static readonly BeltConveyor1_VibrationSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1220'
    static readonly BeltConveyor1_VibrationSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1222'
    static readonly BeltConveyor1_VibrationSensor_EURange: string = 'nsu=' + NS + ';i=1223'
    static readonly BeltConveyor1_VibrationSensor_Frequency: string = 'nsu=' + NS + ';i=1224'
    static readonly BeltConveyor1_VibrationSensor_Amplitude: string = 'nsu=' + NS + ';i=1225'
    static readonly BeltConveyor1_BeltAlignmentSensor_Measurement: string = 'nsu=' + NS + ';i=1227'
    static readonly BeltConveyor1_BeltAlignmentSensor_Measurement_EURange: string = 'nsu=' + NS + ';i=1231'
    static readonly BeltConveyor1_BeltAlignmentSensor_EngineeringUnits: string = 'nsu=' + NS + ';i=1233'
    static readonly BeltConveyor1_BeltAlignmentSensor_EURange: string = 'nsu=' + NS + ';i=1234'
}

export class VariableTypeIds {
    static readonly StructuredArrayItemType: string = 'nsu=' + NS + ';i=1'
}
